apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopia-repository
  namespace: kopia-ui
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: kopia-smb
