apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kopia-ui-secret
  namespace: kopia-ui
spec:
  encryptedData:
    KOPIA_PASSWORD: AgAu+KyZ1PlhUjJyUosp2WlWZ0Gp4XsJxmUYuMlK7jwaFnz4VFXZm4F/7ZBXZ87qi2JvaVqb4KraSb4ApoRikCH/0GqvX9ZYy2LCetE1AYwfan9mWOVKh+rC9XUmJ+CnK3QPJcQNfizGGRpi739ApyYi/IIAmSGYVOBXUAUezrtQsI2WxppKlB+uYf7WAhBOe9LbMz8ceTGuX6grz/23FIvSzDCH9+6JwcjhzKtvyOm+XxXSTtV+5YiBZPZbOdhQk+oW9oBGbqyyNBsI+N9ZGSMfsDsiWhljcu58uHeDYEsm5Es6n9LTOMWtPC1qf346tPWBsJvwpB5j3n5/+oV/neqVw+xkewnZGgbCNjssoN78dl0Zn1R9/N86RA+p96KZiPkjB5PTS3sD5S45qjVuIpXXBuJhI4n9qv+VdB6qnsg924bv+aTMfgohaemGpGJNFwhiFaS/drL64c7cDGECFnZam8Q9NKB/skeAKvGmzvEZgy7+PbjRGtYb/Nga/zMc8kFq5DFAW5JLwmT8Z11CU0izV7JGmwbkNXa9u4unfo6VvmBn73viz+jpJrmb25qSZVBDgDm893gtWYU+lkN62Vmfx3lFNaJFPK2/RvDKEoIo9p4Ge2pm1fgkHkQBpphIWnf/V4R0aMtRaeRLHDN3sFKuinDwNOJyBUUfjnfaiX+3zAfWKYlz6Hs+G8F9Y90j1Ar5qbCcdGLEyKIO2Vqv5/gi5AGj332PrXZd83/u0VAHre5FIFCPV3TvMS2PfT/vgdM=
  template:
    metadata:
      creationTimestamp: null
      name: kopia-ui-secret
      namespace: kopia-ui
