apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kopia-ui-secret
  namespace: kopia-ui
spec:
  encryptedData:
    KOPIA_PASSWORD: REPLACE_ME
  template:
    metadata:
      name: kopia-ui-secret
      namespace: kopia-ui
