apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kopia-ui-secret
  namespace: kopia-ui
spec:
  encryptedData:
    KOPIA_PASSWORD: AgBQB1eqgfjHQw4CDeso5nBScJIE28uNqCfel/z9T1D/knlDan8D5ZNH2hSbHOl09JbBjP3di0sVxb8oGPNGTIoOX8CMm4bvw8UzN9+0G+KFM2gSxdfbKWeoDhx1e5gaswUb3ZWtw8afRsB19hINWvrLxyE1cQG0KKm1EDGO+y0YLxx8/oXMdB57pCqedmJqLC4mqf9SjtNOw0Ad2iKzLw3CB84k470RkbYRPErESEnDt+4Ctk8M1yvkBXAlwf72TeNSJDW80Of+I/Agoj+R1PepU/FbLbkq2sG/eAHRErGDLF75elum9y9Wk0exUUkO+rQOrbkQ+xT3QulN6hIWMsJNjnJXlwZLvP7oEdahPpx9PUy1QrvjH/gUCkl37lVPUKBMlf6ouTHibesWWHFkjFk7f/tj4HC/CAhHb2TtqizVM3n0YGEbXNUg7nD2dOeGB+JCoVQW4aX5618WYrxBNZAJfTFNdQTmZUvD+mgRhDHcZWThIN0ygqYVDhVUng8bNwy4LOn4C9j3bVO8/4hzjI2RshfAQJT/00MtZHDD7wXFLs38ySoOty5LU1vAa72dm3C0lGFSEqoPlBQww4lPo0vg9htMYk6oszLNYzpSAqmX7cdjmNfzkrTw6/f7ggGhnMcuA4g8xSSaDsL9MC3GTDMzrEukPHAuUjnwmeSFkMRVAQjKFLNa5SHGBR5gRKHUxN5oC1i4lRStpbo
  template:
    metadata:
      creationTimestamp: null
      name: kopia-ui-secret
      namespace: kopia-ui
