context: omni-prod-talos-prod-cluster
contexts:
    omni-prod-talos-prod-cluster:
        endpoints:
            - https://omni.vanillax.me
        auth:
            siderov1:
                identity: pboyd-oss09@gmail.com
        cluster: talos-prod-cluster
