apiVersion: batch/v1
kind: Job
metadata:
  name: llmfit-single-gpu
  namespace: llmfit
  labels:
    app: llmfit-single
spec:
  # Set suspend: true if you want to pause this job next time so it doesn't run automatically
  suspend: false
  template:
    metadata:
      labels:
        app: llmfit-single
    spec:
      restartPolicy: Never
      runtimeClassName: nvidia
      priorityClassName: gpu-workload-high
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      - key: "gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: llmfit
        image: ghcr.io/alexsjones/llmfit:latest@sha256:9adb79346867edf8be40fc786815997b13dbdfa3f5d1aa30151e6d209e9ad579
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "4000m"
            memory: 16Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "1000m"
            memory: 8Gi
            nvidia.com/gpu: "1"
      nodeSelector:
        feature.node.kubernetes.io/pci-0300_10de.present: "true"
