# External DB password — lives in harbor namespace for Harbor chart.
# Must contain the same password as harbor-app-secret in cloudnative-pg namespace.
#
# Regenerate:
#   kubectl create secret generic harbor-database-secret \
#     --namespace harbor \
#     --from-literal=HARBOR_DATABASE_PASSWORD=<SAME_PASSWORD_AS_harbor-app-secret> \
#     --dry-run=client -o yaml | \
#     kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-database-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_DATABASE_PASSWORD: AgCSIjXlQfcfFuFzrh1uYnpjGDkQdlZZQorEHAjMoU4pLMtfUP0EakrqZ8U6Bqz8ytmOTMxVbpkddYgbi0vz7HNjhgmDFLaAOTXF8YthEEmoDtgYsz0P3kBjSDxs5V7172UZUpakEDGFc5IIaZESaamMkIRD4dsUBJJydM27+gS3sziKzInTO8d5xqsdiLRBxUJxPnavQBPGXupzgXQXFCeduNoSM+ZYbDM/KAiz7mmmV4beEuoTOBpmps5UyTa6RSa+M1SEVLgn5VGhsBpTEGWkGuQDfhAApOKweRkWxl80XXFOerz5hvKbPKYIPAL9nJzpK6n2Vdi+ToX8vsRl9gXQmIELk/hvIBrvpvpweJ2JK/6T+mYDjItC4o9eviSvsHd8d8OrVaF2nJalkYx/3OplyMceWD0GIbj3mMXpCYJaBLez+bPzvP1OH9WnpWK/sEFlj6NqCirT7UNHhU+yB9MoxOoJ6Y+N/o5/dLXJHXqck2MzlEx7qwHiObwH1WUiM76Pr+sSOyD1epoDbVqq+c/cShxU6pRdhL9/QDuIH/qJhJhUuZqkFY45CqqDu3cJWPZPvvgGAYarqkF8EPdKExEHcvpAtmEa0te45OQelql2WI1D3FciGSVL5LG1l9Igiyu3LmwVrXu6/8huNlP9keT/1bsPOiYZCH1TKqDc9j4Ag7f/vk6fWN7FvrDEUm1nrHiQeIMLKlHlYU22vtvue7c2wP6MRtQbHh/3i4uqQrPlyQ==
  template:
    metadata:
      name: harbor-database-secret
      namespace: harbor
