apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgDJApmhwzp4EXba7LCKkLhmXRfO6PEAJOvlTYt0Icl4eRriVx6PHnCrsgWfSteBpownuuoqMiiqnjAiBHp11gwdTJBIzziLjV2IjarzzN3NOMPr8Wyp7huc6kzHHejt/lae6UnIY4zuo8ZF0S8GQecmJkmlu37ucZ7ZNLNTq5IBe8EwhQfJB1ZkkLgblHCdqykUzxymHtYRlQGJXI1iMaRq1REzDZQ7tqPpMakfjXFTyZ+MXdgdcJ3qznSWL7WICWw38fn6lQN7ywfKQo5fHjBJzzjE/AVEBNJl5R/2icjo+ETFGHTXHUFnu6rL/v4ZT/Ws657qtijOohTopBSkco2kaVPBIiZpJjGTabyLeOcD0ohDSyDSrwBEMWmDtUa44ywdyAZ06wttV8CpymM0fFcyIXG9CrEerfoF57hrG1M2ZBYuWpDHOLzZU3Mli/hL+t4u6mD0oQHxQaAFNNEZRlVmAZuZQIw8LGCx+x9ORKmrdCzzXjgBtniS4jpp/cJQ5G6S3liNMwkvJNePs2h0uGemAk1ETup6KNJdbuOxcbdajw2wbP9qvQyGP2ayWm9mZTh9bBmDsMsmHq+iz+ukAXzfJKhnRjD616UiEstUcoFrg5SkWEnLB8KunF7IizlTOpsEURQzIgp6Uc3j4xOpqiTqc3H45N/fIZpa09BwxQoKLgQmKclWYAkM1x6//SHx4CnmUIMrqoX4
  template:
    metadata:
      name: harbor-admin
      namespace: harbor
