apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fizzy-secrets
  namespace: fizzy
spec:
  encryptedData:
    SECRET_KEY_BASE: REPLACE_ME
  template:
    metadata:
      name: fizzy-secrets
      namespace: fizzy
