apiVersion: v1
kind: Namespace
metadata:
  name: posthog
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: posthog
    volsync.backube/privileged-movers: "true"
