apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: posthog-secrets
  namespace: posthog
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    posthog-db-url: REPLACE_ME
    posthog-secret: REPLACE_ME
    encryption-salt-keys: REPLACE_ME
    posthog-db-password: REPLACE_ME
    rustfs-access-key: REPLACE_ME
    rustfs-secret-key: REPLACE_ME
  template:
    metadata:
      name: posthog-secrets
      namespace: posthog
