apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - namespace.yaml
  - sealedsecret.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

configMapGenerator:
  - name: wyze-bridge-config
    envs:
      - wyze-bridge-config.env

namespace: wyze-bridge