apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wyze-bridge-secrets
  namespace: wyze-bridge
spec:
  encryptedData:
    WYZE_EMAIL: REPLACE_ME
    WYZE_PASSWORD: REPLACE_ME
    API_KEY: REPLACE_ME
    API_ID: REPLACE_ME
    WYZE_TOTP_KEY: REPLACE_ME
  template:
    metadata:
      name: wyze-bridge-secrets
      namespace: wyze-bridge
