apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: project-nomad-secrets
  namespace: project-nomad
spec:
  encryptedData:
    APP_KEY: REPLACE_ME
    DB_PASSWORD: REPLACE_ME
    MYSQL_ROOT_PASSWORD: REPLACE_ME
  template:
    metadata:
      name: project-nomad-secrets
      namespace: project-nomad
