apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: posthog
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: clickhouse-config
    files:
      - clickhouse/config.xml
      - clickhouse/users.xml
      - clickhouse/user_defined_function.xml
  - name: clickhouse-config-d
    files:
      - clickhouse/config.d/default.xml
      - clickhouse/config.d/keeper.xml
  - name: clickhouse-init
    files:
      - clickhouse/docker-entrypoint-initdb.d/init-posthog.sh
