---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: audit-ingest-secret
  namespace: jenkins
spec:
  encryptedData:
    token: AgAZytmDdiqPVaKbUpcfGa6pwjhjqRlSAwum5mCktd0IZ7D1YDtVMXu84OA8/GJbVIMY6oazzUe8lcowAdAc9q0GK0wAOanf9LwzT0RWnJDsI6cnoyi4YcIAjDNEoGgUPrRLT5M7o8a0n/rPLe5vsk+bKVL3iHYlXb8PH2xBxlQKtRA+dcpLyKxrgM5DOmc5cwYPLu41L9xmSprkQGixTjlppj0rfUhmJc590MAgQN+yUJdUnsMk35NcfBW0tKjnC3VbN1acQRAlroiuXSA/XtT+2ASBYKM/CPdUFseC8bbcYU7uL0e3rq4DiYm7PAOIWuJjzhPJzSLKSw7gvyL46VI90dT5zaM6/keH7sydqKG+rtH1K5SuvRzbKIYPwGGHq534WThstzZmYO+q7KLIGikFN0/71iH1C+ziPOjLkRQiK9CRFPj7DBAP5GSoEIufvqd4Q3xNKZwx+S3QxHyuelHL4UClgjJgYJ+RpgNJzUmo5JYLSwtkuGXV8ovWmeZIQ18r2S5oaB03OEUiWpJddqRI7bT0Pqy7/yN2AlRQJryzpPc+PJS63l2iDD4hmQGwFeSFnSMLMTx+KRIGPv1d/GE0ZtRHzBvTB7NtUEQMZdhynlazzh8t0nVjHQvnNIwIHFXuiP5t/MQPuWc+S74Nt8xEPphoPaaXgIlt3POB4ba2sU1rWlwC1FYcTQpMIvNkxR3p43DdJEMZMiK+LLELNQPWLFGDFVvem8urtdBGo2ga8QMCj+IghI6pisnfn5mJgMxsy+Nm9mjYSG7hbjTXzCFH
  template:
    metadata:
      name: audit-ingest-secret
      namespace: jenkins
