apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc
  namespace: jenkins
data:
  01-kubernetes-cloud.yaml: |
    jenkins:
      clouds:
        - kubernetes:
            name: "kubernetes"
            serverUrl: "https://kubernetes.default.svc"
            namespace: "jenkins"
            jenkinsUrl: "http://jenkins-operator-http-jenkins.jenkins.svc.cluster.local:8080"
            jenkinsTunnel: "jenkins-operator-slave-jenkins.jenkins.svc.cluster.local:50000"
            templates:
              - name: "default"
                label: "default"
                serviceAccount: "jenkins"
                containers:
                  - name: "jnlp"
                    image: "jenkins/inbound-agent:latest-jdk21"
              - name: "skaffold"
                label: "skaffold"
                serviceAccount: "jenkins"
                volumes:
                  - secretVolume:
                      mountPath: "/cosign-key"
                      secretName: "cosign-key"
                  - secretVolume:
                      mountPath: "/root/.docker"
                      secretName: "gitea-docker-cfg"
                containers:
                  - name: "skaffold"
                    image: "gcr.io/k8s-skaffold/skaffold:v2.15.0"
                    command: "cat"
                    ttyEnabled: true
                  - name: "kubectl"
                    image: "alpine/k8s:1.31.4"
                    command: "cat"
                    ttyEnabled: true
                  - name: "golang"
                    image: "golang:1.23"
                    command: "cat"
                    ttyEnabled: true
  02-global-env.yaml: |
    jenkins:
      globalNodeProperties:
        - envVars:
            env:
              - key: "REGISTRY"
                value: "gitea.tuxgrid.com/pboyd"
  03-security.yaml: |
    security:
      globalJobDslSecurityConfiguration:
        useScriptSecurity: false
  04-global-library.yaml: |
    unclassified:
      globalLibraries:
        libraries:
          - name: "jenkins-library"
            defaultVersion: "main"
            implicit: true
            retriever:
              modernSCM:
                scm:
                  git:
                    remote: "https://github.com/pboyd-oss/jenkins-library.git"
