---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-docker-cfg
  namespace: jenkins
spec:
  encryptedData:
    config.json: AgCF6ox90YeuN08CPwYKBJhBUQiTOLRp42hif5PI4l6FMuPAzEKXYoSXP2wu/zCBBPXOeoTKsprYLQbYSkdTRriCBdXK4qdriaqcXOp28XiXjEp/5mWAglcjCudXRqm+P/aHwGqw8XfMS/RvyxhLZFsAQGfKgJ5/AHEdvMy6qWp7J2w1GQvaigVLFoDvMTsQx4K4sXQq/6uaYsZ6FckLf7ab16gXG4gvtP6Ejcdg4BLK4i6U4x5J4uDo1mZIKy8T7Efy6phHpQ/Zh4CAUlzxmnKZrnfYdYmnhNHxuaq6K+Mdle/vq2XvxOye+XUt0DSqpN21JKKctl1G3kwC6D/4QgJZM/e6yaaEDs5WG7gBQpo525mDq7Fd2LTP7fEQf/cyjjlq3+Eqffo7dCQ9h9Oq08LzsV1c6IMyLD5v87t+LDTU3qGWygFCTymxaBfC1uuzBboPQcs1Wim1oKrQvJ96WrCBLdYPqLwV+M7CZrem/X1GeXYVBKGfExlzda5YqI02myLBZKq67VgGFAJApJgoLfEV0fDN+2ntgeavATs8V5cBaXKvpiXNwovsVI6L6Qa6p5or/R8wMcH8lqObmQMghnvjnNOo8L/F9/lthpbsdmOuCd4m66LeoQh1/lGBzRWd335HlpfDPx28dVpG2XBW5FSP58ytrMNzCy6WEJclit9QXgt/4bAcDs4rXMK+Q7Tc9quqvrp0OUk46JkfZBuRUcHoEPYofJoCNy8xbBW8NyQ6AURNrnAfREyfGKWduTDYq7fhz+eErDiRMwb0MfJCW/+iHj3vQI+Lcw==
  template:
    metadata:
      name: gitea-docker-cfg
      namespace: jenkins
