---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry
  namespace: jenkins
spec:
  encryptedData:
    password: AgCtvedBUGvpwWc0DSrnV66gWYoprQpO0qu3z1NNzgdYFjssz88U1JcpLc9P0sNsfQfO9CdPELRCHgTn7ms8Wrq9aA1a0wTggIn7wBF1q5JSMkr3YimEfQ/MLQmf28xU94Dv4fwSZcUUIOs7JwFU4Yj2pPd5gmRTnlCDXWvyMd50xo5TpaoZ2TZ7oxvHkYaCrVldvacrEpJlTBPyonmTsVP2T7DfjvSAI9Rha9r5FHA1lGA3Hx6iCaGRTzbuK51tnBt0Us2Idem3HuSjjTDkVDa7q2F+VZdPOX57lGuqeyNT9zRpMmn1COwhTnx0P86G3SVGZB8Kek/1V9orB94yzm1ys1QgX3JlHbj7LmWQUnd/5szzAXw8mxq3w8xtBviFppIOoPXihKXza22CwU0AATmUyaoyR0YLCa/PfC8Dbme0iduhmpW3qlVQnAM7aF2+SBynImXxkPM4GbD4NZ9TTw+vRQzwqJSwVVnoaZ7LPljDUKvat25d9m1LzBUB+aBrEwoJ29byr/gp+18igOaXdmLDwIM204JNR3n81wMiU5T9T4d75FY7SPQox9QKZFLOrxrY1iJmlRJ+Q2U0l7/RvuMYtoBNAU/oF+qLR+Am6bzdROFEySKma4zJ3e0YDCXjCeTbUzG0XFdw7OIeN4KpL7uk5euJ83HkDdxE0LYhWNufuJLzj+8IQNnYOZMfgAjnw7TSOdlLGyDfJRHZv6LhUw==
    username: AgCgTnI2CGfRutYWmibEYRTASPdMbSNX5CrKaZrwZa091UQi01EhxNRoQ/37uF8nsqnpfFrnsKPJ9ARiEqjM/Ep+1tLMDOYbpWNpUJ7D4xuOXP3zsE2P1tAztaQKcQkJtjJNVpl6j7kCOE5y9K4FojlyuiKcsy3xygXllaDuQEFMitIFUSmX+GsP/9fLXGj/gPvhBQziX9JlnQwkzxwW31JUnmPFX0PnRjx55yZuzT7lSD/ck36NiofkOOUmifkOJDJys/yTR3a7BcimmKzYSXA7FFBULXELM3qGXaHT1unWsJ3D7tuGlQeWyh0Lq4C9C6MlY/Sy5gruOiw8mIY06qppJUZ0pgKSDJr4uQmBDm47qdYI1lTnebK9hZCog9GfDQH+RCcpTAQRGpm1AgFJhRBH29Lr0W79LpmngWZA+p/UrfZ/AlEVYEfTKEKHHA1D05LOcowyIFjWFxPITpBsnuB8nu/Xv9dK0izJA4VQLFeuvEPZRUu1wGIDfPX7ZjHY9tp3fTo22D1GvsEG5pPYN7LK7GoR6gC7vlsiyOnXNGamwUttKEAJc8u3r2Wz0BCbV2XmbHdNrm7++FHBRvlN8TVy1sb384/lPSUYbHcHEcNa5xuRXsjXKyZlDta6O1Kv4wvharrDBgQUmy4+7nqLnQ8JtoHp58vvXWRRJr0xzdpeAK3668JENUz2gBrvEwA5gto3v+D4Mg==
  template:
    metadata:
      name: gitea-registry
      namespace: jenkins
      labels:
        jenkins.io/credentials-type: usernamePassword
      annotations:
        jenkins.io/credentials-description: "Gitea Docker Registry"
