---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry
  namespace: jenkins
spec:
  encryptedData:
    password: AgAej8PUvsZ06n6wQCfVB9QpiW0DQBOF8c/3EWmKHzmYYAt46FZKaRvuDPNAYVQtxqxp3DWo9tLkCQhExpWBzeiPL4A4BeFEZeyeJZCmIU9S6+9qw+4jacKf/EwEu//usJkNJpJQUQ5M8EYLfZVCJQCXzpyA3ze6grrcwR1SRiaKDhlVYFSiMxyC2I9+Fx0lOnDNofpYooiSbm1HC6DAseXgSxqAJEhLfDtOrkp5ahrot8V9/yodhFu39GsWdmO3fHc0pSX9ydQazFeS1R1yhq+X47S+dnTJFc0BCK6WnhCmXmDgJnRveAQDHv5yiIcbYcItLKkt5S/Xhh4yobiFZVlhEK4KdT+gcGKwFamtbKTkUYwUUad41Z2aKNLjN3JvCN/O60IFRSNdQrrrLRm1EXiNUzQR67+l2jwLXaVOYnzpIT9yb0NtJa0gIWnsrZDjbpJAQvnZ5q5K6g55d0kDGflPSDY/N6geVwe277uqG5Ypje2vKK3PzfIWpp9bCe1j024ingZaHoO/a4NepgIcsnyP0CYuKZze/QKDFGMkhQT4QnjHzhb/GnnBW3K72s3/nwxwyYOtdnAvyDlPHG34BdxkoDD9ER9pN4xrqqBBpYnN8OG//uISBgvPbMo+o+mjUEFomfUVyefo7wDvYR3UcIlzitazGqBTyUAM9SNdNE8IGqAN9a0VwyfVRg+eXgHNkfpt+C3IsBDn28a+GeA0sw==
    username: AgAL1JSSb3N+4Od9SXdOMJk5O4BxYrvgYPdCkYqV22ovBDFZ8WyUuYKmTIA5ApWaWrCa6ZVmpeg9nYT0uOg5RJxQhTiL/NY+Yq+VvQ+qLz0OnYVqAXDV6p/7Iq7DhxpffTy7XXtSFwZ6MNsS/3n5m/ZjO4YGVFfPOus2wXEjEQZR2tKMTLPq8UebrzztJ6+vIOZTSgCoIuVSLRpqxrFyIMHbKeKn/AaJ6okk40JFyD0p5de2NicF1APU4XPUhLveXH28FWD+/GloPkJd9dX3ASNKJWOGXMlgWJJ47rBttUcF0pKLxzWEER2vw54ucUkSrLmk9y1MUG10wcyLKZmGA8vO7gUSgyt2z++jONSO1LF8jPNlHc6bGcVfWFAeOLOvuRuZXXZWYThpKIzXmbKQm+7WRWk0A+AZlzRPt1lmwTMjz3HyeML0bYc6H3ffQFhrJPdJjm/mc2F+jlalg4yIs8QQpyF9uiaAgOxUu6dSgoGSuMxSxIVY+pLRceVbiPS7Q5CtnGIOp3J78lHySibAEm/wERIomdGbunjKrU2H2YawgSlOpFg+I3B7tg/cL2w02tbsW8f4NSGn83sWqpc+x53fg1eTjgn4+lu6riTK2UEvWyecHIB7pA9ibB8ibls+CaOjkoLTYZbhWzfZ1NjU2W9zNMscugsR4q0dbVatPh4zEjweVnKP1Ze/7DO7LO6Vktgcq2FNbw==
  template:
    metadata:
      name: gitea-registry
      namespace: jenkins
