---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-robot-platform
  namespace: jenkins
spec:
  encryptedData:
    token: AgBQ9P6P3+Gtn3syxIYdzHhs0x8PmetzTLxFAi9Dd5UqFdRqXTmVbLeOJAq8CVoUrsW/WA8JFiM11fVdi0Pug6Ch/NbGxwezEU/UhZDkW/hLughr8L+2NWY+ET9v6L2SIgxpylXqfWipaDytQsSOPOJpz+Vhqm8wFJcETWy8rHpf0Zi4N3c29ufg+GPzLZyu1mkksAlGay05I3G3qCxafr7SpV1OFBURBBBCEmJQVmnqwXRf5JWNBp298r7z5XVini0SLQwTif8kCk3SYQMze0Ywy5H7iS6utR3jfyuVX2IlL1VeJc+1bDOeuOPP6hPQyHMGwJQ5cuz3CStyEpdMfYaKljkYlVp9WRPyuO4bGGqy5PcdD3QN43zvXpJ8Z6nyV5MpbwvZ9AUbppBgW42eQ5P+DY5EKD3n5JBTOU0SZkaUMjnkzFOP4wN7AHYI38TMUAv9KBByvhxAdxmse5HqE5rK0C/UIASpc8vbjon8V7KhsNQ/4W0sFafAqj58MIZqzFfGWTyxiyMI3kp2JMCs5BCJtuDSRxs8U+QZ9sBCbueVaKZhNYLuJ10IIV2XbKsOnsGpufMU/L0nh2t0FGddeYs8y0+Zu4mub4DWKUT5H22mMT0IcWPxCRUK3lWVQtCyPnkBqIQxeA0WSfWK8iyjSKwN0zainjkAdbiPQTcgc1O48kw48KgpPFj2pjEsy/d47QTI1Jq5pf7W5sVlnIgBfZzQNhkjEKNVQbhabKuAhJf8NA==
  template:
    metadata:
      name: harbor-robot-platform
      namespace: jenkins
    type: Opaque
