---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-docker-pull
  namespace: jenkins
spec:
  encryptedData:
    .dockerconfigjson: AgCytslz0obHrhYyUUWBPWPKyp/XRHZzbVcKu0gHAcWgi7+xcCxmyy1r0DO1dll+LbPGfXPPdr3p/n2hLdzhGkODNjlpoiwjQwcOhCAjBZcAo90f2aqPcUKbS7IRvbUVppZqafBH6zjN9kfn5Tg3Qql12DBRA/Sx6bA8DjoNbnyPUIkSpFeU7RqXRi3GP43+L5m8c8kAZNGJBDSei3NfB6uk+twgBPPgqgnuKlCn4VNW6z0/+PSx9UtVVH55lh7Q6itDvVckOJlya2xj6W9J22V0mxpqbcvA++fej+vuNKgI5cfqZHHM+CElFWz0UDdnv/Ok3VDDFkyKHMRl7y5hgjstZ5mxdxQQjZSyE2QwBUVx7Vo7+Kp02ZSrG5XRO+T66Q6oMELb9hOaS4AnlwdfM4Jkq0qV2QV5uxjhydWpGNsqJqXjgAgxZSlYJMUQFZPCnvywofZqv0bxdAHqd9O0S/yCt9O0j5T6i5jZthOXysIFIriN+Vt1etj5t+jIjunKjd+iB5iVOL0MZxkRccxENdPb2lFvc6fcbPLiOc3NpD29F1o5/A8UcSfn3qYS+lvPJlbidJYn6gYNRpq+2k0LrRy00Fi6MgelHAeBDApchpTi/RN+A8Xl5u0j9NO5OqO22bzzumXRkJp8SeVPsQypEKCizQ7TVK4UCJGNp5PQyKs9UPIB0RSbzEEPL3rkoY3p2AP3F/yPwXwHFcapLUhotdDKDgyEAZQQfSX4bs64fumxEQvSbmZMYUqrxoHxs/ld8sSgtyP2fsI1tbnhqF+89fIriBN5cfi/0AzjUXseZv3P4GQbXz/3y044jKwzy0BKKwSLBE2FUKWzymrrfyMfxu6+Fqo8mFJPTX8ONvQ1EFVmtXGg+2CxU+f9hVNtdu/xo5l1M548KpXi2HL25J84DprrU5detfDPT2SH5s1sU2YZyrNi6cm+z6gcq2oWPe6GnPvso+TVy0ejTW4D
  template:
    metadata:
      name: harbor-docker-pull
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson
