---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infracost-api-key
  namespace: jenkins
spec:
  encryptedData:
    api-key: AgAPyyRGhn/vubAy6A0iQd4uhbYjRdFxvQnmwLHyPDg/nF/3So90tc/DmK4x7++e/WvQmbLQ2jqjPFgv5NSBterYn0rR0fFVkrZoUoURqtRx5x2y3EXt9v5qad29lpSPg4Sh4xy1Laplbg6V36NDFPTMwhUmcsm0NwCn3929hS98wF9cpXUNI9IAekLVkcpzNqaoD9H7zYdwjTDv/FElscwXmLNrRe+xSc3c9Mggi+TGmoT7jXCzkr2s4ibyb9rgGqGhZ6FNOb9ob8/u/2lc08X8h6wXELw5x8IeAxkK/m34Ns9RmdR6n/Mb8C+I9T8yAgb7bFBMt1+ZdHb61DhMkm6dhhMTtPDFM9vEM5ykoIUN8K042d4xY0vOcv40aRfa7LmPciqv/NZn+TIE5XWk6M6u+zjaDfJAXQjZIhcdOdSlijdO7H85/bFfCg9BXnjZvZAP/HPhXFBQpTtjDnKAO63fCLWpQU015oDaoGqX3UhXhDF8ZwBCoEQCE4BMVshQ4sit8gMj95xdY/t7dIIr+yCKThJj/L1Dfwk0dSLWq1BkRsRZUn5Rb/Spv89H7/tMw2x1TSW8wS2x5zRp5PSPbRBaKQzyBdd74Lz/56dXGF2eTtmt/Go6FlKzsbbLaqwoVerWEcZULJLl24EmfztaZ8x5zt6B013keMMier5XaD3Wk+c33ZPPyivDBYiLnix7nPf3UGUyXqcJo/r1KmgUpkwQ
  template:
    metadata:
      name: infracost-api-key
      namespace: jenkins
