apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: jenkins
spec:
  configurationAsCode:
    configurations:
      - name: jenkins-casc
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.555.1-lts-jdk25
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1500m
            memory: 2Gi
        env:
          - name: JAVA_OPTS
            value: "-Xmx1024m -Xms256m -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true"
    plugins: []
  seedJobs:
    - id: seed-job
      description: "Load all pipeline definitions from repo"
      repositoryBranch: main
      repositoryUrl: https://github.com/pboyd-oss/talos-argocd-proxmox.git
      targets: "my-apps/development/jenkins-lab/jobs/**/*.groovy"
      credentialType: noCredentials
