---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kaniko-docker-config
  namespace: jenkins
spec:
  encryptedData:
    config.json: AgAh82Fxnu8//E8KYUE/QeZM+z/MC+hUbHz8Vub2Xv7Mjhm+XT4Oql+Z/eZpHE0NkUvIXN2mC8YjRKlF1Ee5NN79lBWv7yWwZyGVc/LqQws7BT7y7rF7sf5OB7bvaRQO3tv3Ak4gPT0vS17gqr/Ndv55reRjK4Fdjt5GKXEvNgiYYR5XGT2UMjZ2yOxTU8T8BdisVMjY8vAs/kHhgkkKQbCVg/IuX68ZHgOv3G4N70jCpPRRDQFbLUL3gtt6XU0JFOHJMi7eDxFo4wJhCbtBDSnCQolwTYXdIDn0oRvRApeSoABpOTqdiqDbniz0yg/WNRyItcAgjydTkoUc/16f2e0Dj47bSDR97RK1Bup32Y4rjVrpfTjHZC3hA3Vyd5aCa4yPnfzCaa6zVh27oLI3U2y3CU1QZ1MkKp95raGmJCDcZWaRMrgtGvpYMMlyzsBGEVK6tAG4ObhEA8aVqqtRTIGmIxB+PEDKU9DzcBoyc3863wDh+yZinovl2CrvYBp+d9gCp+l3FhutiFA8PNZgZzY9CzEIcgc1PUlHDasjSCnQbVepKWT5NQJgwXnBi91Zc6LlxtVlSLcy2uRYqv3FaWZmoom37PJm9EurmaF5p03g4zfod7tpLD/9YvYbvAqxICcHqynn+ITVOXhPQY6PrmhIbAUXJV0/Py3DhpkJWdp1PdybOgY+gH+9Sw1cLw5ThvkicX2Uynvh++adAUDEpyElhoM99hCSCtI0jIYqevWBH7ImWBAUhvn3++lw+7Xl/991g+sOfyLrMwC+7OSYhnX1cULfZ2Zq7g==
  template:
    metadata:
      name: kaniko-docker-config
      namespace: jenkins
