---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kaniko-docker-config
  namespace: jenkins
spec:
  encryptedData:
    .dockerconfigjson: AgBTwiUGtzTWUyXJ9k96HJbd0obKAgj7qm/hIkXQXnUauHhwCPvcSz8pslvgFdFVOEk3Fr4G/2aAI9G812mMda5QU+jcJjCqUUff22Y8ydWnHMeSXVzoW/amP0+vY89hmFcre0pjrSdP00uAvjSxPBt6dK4hROWFIOvKfwmfyPzR0LpCjw5RHJp4ed1vmYNdBUZvrrYSswrGPD5X40L6Tknv1nbrpmujPPyMFDwjJRQt09Z3XpAgONXzYQWbwoQenzV2UsqOVz0R4BsbHo/4O8b6zoNiIF6RQZ+R2vXZW/OnFHwUCeDFDfAXA8gl8x6x1QOA2aIqZLX/N5oCWWOPsZMfWR/hlgsmHhTw9iXUivTGeE67d5Qim0eSvLoC+JY7+Baqgway2eoD0wSFnC3HEOjh3BRttGwYZL44oHUHqS8xJVxfaWgJv2k+Ny5pcE+XHOy9CG6gISqIqfs1CoqVH2/yEWm6M/lVYeOcPs+TosMNq8nV1QZJQfF8fQw1WB/xfOStnzpXC0QOKpsEUtNmkn4/GWwtSiebigLKuPV611mRNhgqWbCuKm2LX5HmAdYS3daoo/mFiTuxF/qWvktNu9+yFTccULM9gVXn5LoZVUau4pYJEuJnMoITT54ocC27+lyxOkHudhQbkd77n3iMD6t9XudCYopgB5Vq1aVI/j8Xc6eVYKrI+oIyj+/rPDO3fdM/upO08uEO2pOyauJiEvNjOPa7raE+bO7RCDwu8OH+3N5axAT4907uttVLBuDUXrdwxSlwOOd0Ih54TXJfgYuCR/DAMqGVFVdSWdIM9SwPxu5O4LKcF29KUbgifouC5T39IrGy6pp5G+lDP8sDKOrOxewkrLMk
  template:
    metadata:
      name: kaniko-docker-config
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson
