apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
  - pvc.yaml
  - rbac.yaml
  - httproute.yaml
  - casc-configmap.yaml
  - jenkins.yaml
  - registry-secret.yaml
  - gitea-registry-sealedsecret.yaml
