apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
  - pvc.yaml
  - rbac.yaml
  - httproute.yaml
  - casc-configmap.yaml
  - jenkins.yaml
  - gitea-docker-cfg-sealedsecret.yaml
  - deploy-sa-rbac.yaml
  - cosign-key-sealedsecret.yaml
  - token-service-token-sealedsecret.yaml

configMapGenerator:
  - name: jenkins-groovy-init
    options:
      disableNameSuffixHash: true
    files:
      - attest-build-listener.groovy
      - seed-token-service-user.groovy
