---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: jenkins
spec:
  encryptedData:
    .dockerconfigjson: AgCnQ/oWFAUii9bRbZPX6W3PQSr1RI0mMzUZMloHo88laTJBjCwQsYx0U0du3qfcxtOVBQirVs1uKWAiHcWLcHfKPMkXcJtjU66ISwFyW1jhuD+wytW0IlhXlPrwJR10iLWofR1xziaXB4ITaJtViPw50soXbiH2/ug9uP/gAZ3eJMmCF2RfnHcse+3HL+AuW320AB+4DzEmrVutBSAn9kVwLSKmusEUnbSvjrsMW9r6gZZ9XN57cSTbzs4xE0slenJ00QOmCxUoXUsYOvCWWjAxND1hofmbBWwnUssKmAtywghUxKZqmR9bjckSd9htGMRpUpyUQvsmLj6IJ3tRj/jahXZH41nro5lcG4fAHhZBpl3n7fEub1BbmVr9K+rjZcDHP097tXrTy3k+OF4C9G5WzGmFnrWTMdTXHDjdi2FNv1VPy5pTtHdIBg40dHX752MgjhY/LGG5+fujlNKa96i+WXobuIIu30xoHt+w/KMCVA62kkkj05WUu55dypbzqEkkEIaFX8GHTX5GuHGPsgOIHg7BBQnDFRzqD4aEmFiF+IbbZs2i1WHUKYHNgC6Xd8KV9wT6yYob+l+ugLB8K+/jt1nyWOdtNygeFZ0NLgFsHnUYAYy8BlA7CVxeqF75U6YIMp4ubBr8AWYE+SEzPZG6cpSEqJk8U2Rj2WjSTbn6apXtyyiQX7klac/yuu37W9LIpHA1CutoQC/975SlRFKgmynlnir/TKdCSGGoM+KIKsLHODUTPILKYa6AwyAiYBP6t4x5KZgOuN97eWjwyTlYAS74eCTJTIfuRl/DORvr9EYHKTB7mn10PEeRTzDoTtoFWrdehGRr8WB0KyQ/hkBTM3Sl84Pt
  template:
    metadata:
      name: registry-credentials
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson
