---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: jenkins
spec:
  encryptedData:
    .dockerconfigjson: AgDbK/bZFOaR8dSWUJ7np2DlN1M3j2XLFQp7kVXd17XVsr5oIowzfNMZfRVj66vrsc2AuDAzC4jskz8NSVtgHpY9LK5C/2HPRgUJie0svaPrqeHfOJz0WhmFABXfKBzKQh7ZUT75Q0Cn5haaH+tijtnZ6tqivR3L46XYaDo4eLXzV1I24KPUIorgKbe0uR/cqf66WPioZNXy9WIoj3dE2tlH9auYbYLP/VJA93pEGPSisbuH5Hf/zo3d1hwYkb107dOqNHJcX7pYh+dswbzcz0gBNoZckZp2YJPPsIFhy7z548pQL/iOtg37cejsYdPa6kgSTOG5iWUkRdza9r67JTo04b/7PK3IjHn3jpaf7gteYoP9NGUhL/NHWkfCgSu7lAn3RPKbW1U8QT+GGgk/nSHl6oRgYXRduJzsMf+LflpnpnSDPtoi2PPoZAGHqxEcBUu8esyidMHl7vurK8VFS69XB81z0awW7kWCQyWVkDv8wxNS9Bq48BNQQObivkLbYpNfYyARaE0fP3+Cz3m5FeM8Lp+0h7fJMO4VtjIjMIzfqi5NfuH4QrW4/7i4PCqrrlwA7LY0Sd3lDdBlukm+++sOdHH6+cx2M5flLk/bZLEsnsVwbIK+R3jTmmXQ4mOqEmdzBtt5sv8nVDsjA3P63WoDaIXWxIqv2rl/ZkuvIdlC72cV5UWw64aDUNYDjG7M2FFEbnYSWxsVU+3v4khIaNiTISt67fYEHkQ/N2bcHWZjKwh/pYsVUljL37vFTuIAwX2EkG/dRbHpfU/kAoGgPgk0mw+vNI126uq5a4zHNL5PTLosqJGffjRX7zFOd9MMKrHbslyW5XPUdc9Q5ZQ0qHpui3WMhNzLzPxmYhBo0dm4X19wPlxwWw==
  template:
    metadata:
      name: registry-credentials
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson
