---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: token-service-token
  namespace: jenkins
spec:
  encryptedData:
    token: AgC6SVWzxKTGqkuBz28ENk12d26M5zTe+LxiqC6o1cuPu8wDVFHUGiDZ4WccQPwPoZQtBYi3LDhrNXR/OaLCMn1um2xCocRDTN0CoDkG0XmOXKf6tG0UcLppVxBE2RJYuNFzjGfbx9Ztkow+aO7laaqcZN9Bc+DzSSn3oYjJyCNMxrrFU+G84wVdBkSBtgAksZf1cQ7dLA+1zrbwm6m2xvaA/M8guYlEc4yzK+4PSret1gg+BmaUKFxhvd6WUu/qHIMZQnJAsU75BuBJGsQtGxI7309iTTk8noCHK6ctrneU9A31z2zD/ADWUFQzY08kQpW5CIWWpCeDZNnht7zJFzQhG4BK4/tP9m61suBA5Wd8oEENhoWp8mMIcIeGpShoOffub1i+Ade3zJ9GnTCLXyBWdLz2WYL6fBLhlePzoYQmEEgPlWo03KLVihAI3tCgZDVcXVpoTEd2bWQOQVtwbpCirTZ/lpfd4V/AmqiQqngGAC5GTampz4pOYC07ZxrZI5Jknl6ns99TzoC15RM5dQDH1Nzhi2cVpNcpOWOxwXfCZAkWVCNHcglML2lEgVIhsbuSO1tg78esHT429CUf+ANPLK0hjnMLs36LN2n4LprLZAbddaIgpzp8R9qyIV9z9QzjaT1+7EUeNIecSSwWZlR6QPO7HvPujl4ljmDQnXDAB7eILvDFxrJf1/WWVKf+7ufTfVLMgW8Jm2dDtZWdTxAqDGAktemVj5CF15/DkH3sIFnUCbmYZxlU
  template:
    metadata:
      name: token-service-token
      namespace: jenkins
