---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: token-service-token
  namespace: jenkins
spec:
  encryptedData:
    token: AgAOlFTXqfoWYDdCRAFQc5suvGBd2nOkXlI0PxMsG/hAWHhyK6rXz7lLB7s9ZQdUv0Ht9MRWJ2gWmQVLEflJKs4VmMQ0Jkv+ZV0+Q+0xluR15ALDuKH77eYOFImxWTBK4kJ3A5Za+3qybSoz1XXGp0nqs3UvzqnylQ/KKBhCgFPU03SKUws6mJ8QAjqoEQN9WzBVbc3ZbIye1E8XRGoUZC891Ih/IvID6V3qz3I0ZfnFQU2wjvG3YtqteAWCkKNuPbJOxKgczF59MlD5yiL5/rh/M2kBl7SuhZfW46Eg5/mBJ0cTNNSp7T9Dz53hOdqdpGOlLaH6vp5jkJEnVroCLg3H3hZopOGZFYne+F2jHctbmzS3Wn8cAL0/4B4inLH9a2omRUYxvIdoNyrFmp5MGevQvjjWkW98MUJzBPh5gC/kYbi75nD5EJ68vuXJcZR0ZD4iTcMYWgbxFw1m248rSYBKgzCXxj79iNlobfeZIOOxUlDl784JzYlPIO6OL6KREB0U8rHtF8V/g9NJDrhHJzOL9Yzj8ZkKXoAwvjJGRJcTdHpq7yDqNqy8ofSIZDCNcFA/yQX28NlPW4SLR1IdB9MSZYVtEFoDeJHfO7iI2mI3J5zmdLXCb9Ir9pxjQi7afGVnVfLMLA6dPFRVYEj0ZRDuQaOGKInhrbM+b510E4WJuRbcVpF3uspfi9EdS8MB0w3Ty1AANZfVrrP63Nt8nty4vpoQXLzWFS50B7vOKXg3CcA/
  template:
    metadata:
      name: token-service-token
      namespace: jenkins
