apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-app-secret
  namespace: paperless-ngx
spec:
  encryptedData:
    PAPERLESS_DBUSER: REPLACE_ME
    PAPERLESS_DBPASS: REPLACE_ME
  template:
    metadata:
      name: paperless-app-secret
      namespace: paperless-ngx
