apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgADe7uqhOVxiW3qP14f5eGsmvLueEZRzx8hyI9LpqX8bVRZnzo9zff+y8VgsqxPxHiLZrs7sFqEc68K4B5U3Tyo0JN16SBQ+ViVmgtVuxYWZK2clTggg4iCo7TBVfLyNxbNzEhYLpaUxDGyXfLfiSX5QncU3QJ/qEMyfJYzPWVUyguJ245xzyrJc295OOUxQLUJyHguAVQ97YcM51+CaffxC+zOuTHDXot0Hv7ZlesoD2xarrswyzFK0k5X3MZNCrSL82ykF3oHgj31OyBYkPAk7YD/q6uPtBP2Ny+SbaUQIUkO1Z5sxwTdGYvC3rW0hQWOrXHbRjEmtvgiRVwf7T9whpTu7bIYqm3o6kys6QRp3jj+YAQ+71soKsEsh+d5UQISZHku74PyRkOWwsburKgD6RMdBSlOj4gzsgDMohDmID7n5O7BBHYRAX6lv4PNiouNbrmPghoL9irqg/2MHlTMeEc3O7saPmVxzxb0/7w/jWwwA5n3G+DkSzWxNsplG6X9uXn5agc46sjbOEqry64iKCLmCy1rmEDIeuTojP9Uz0xTCbxl7Wg9m4KjySDb8hm/NV9N/rp4Xgx/m5jhgHcXKvcoMRkqb1Lr1SOXnbKqqW6lOHXW+nlQVIXQiTG8dIVBO3+MyJuDIEjXtL/4qk2Z0US1bSkQ0KEdsl46ZCd1LN0B5mXJlNGxpsQ3btMhLfYD0NWeXFHKcXfablv98XWekeG8cOa9iTKC8cuuK+ZFzEsJXOKlV8HJ+9u85YvmRovBzK+K1w==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
