---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBX4UFJhlu+BXjaIDs6b7lttKLLZ3OQ5VYf8Gq8jyzoJcTMfqUslEgPfkOmg/ETgkceE55FCdY6ysdIvYsK13+PKvdqBlSZyjXD3C0bNRElNPwM+QeFD3K9jpDBEtNJ4GFpzcp5a7UNwC2e4B2w5sOUmA3xCpuq4b9rygW0qDQ/hgL4FeDZjSpfIJtHYDvdF2DfKFOsh6OdJEC3ht1hoX+0ZlZm52vHh7rJpwq7pk7Ia8N0OASrG8DnBS46VxYlWvKfwYPfZY+sR/qcyA6J7+J36zlncse75fO+OFWaqtu5P3f7CV3E3E6QZlaeOcxIOrbtm+8eQJ8+aZKu6W1fCDdQYGVbqnDCEUmWrkF+V3s6TsB9AY+laVKFp+RHSgw190KBXxCMX06QbjQkM28llqjIVGjjPS66Rxlg7ZmLkJS6SlCAwXVldxPmOAghoCMyfqZ9xH5Q3zZ+gOBcVHNZsmfLmGq23AkFh3c2gQ2qkfcXnVqnHFBno5vVNxxdRDmei+J+Ddl2a65VYvpT5YA3buYLmOJJthvlkUyIGwtf8ys5/RUwekrEgPVQKbZJybg+cUIG056t0uD2M/XqffHJ9LjwNlbeQ1xSPNWSpOHv3UhQurxPvtcGcRCHw2QOYCqXbHy+REZYV3X7Vf9lYVEhOYyDEWKQluNhDtDNoVmZefHTZUTKzZgldBb+eJrFHt7Ypgum5a202yzwcQKmpcwH7nGLEzGnBBqPL1biD8aEz2tE4kxf54QRex/Mm51i4S9Xg7CCzE6qrg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
