---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgARzBED/b+/OIOFd0qoxiCnk17FVwW0xD18pCqNy/bYyQm3vqhC3liXkLBQ4zNgJwdkL2aEezcmaiWCCMS/+rIerUwd1/JB5LnIC++1csyKAADhgVNRSzfg/3dA8/mUR2BdlQhXGj/RDvRdED2SgScvC5fqn522fclGe0RaMLqOM8fE7z7j49m7v+H5Hrs/4jiOvgCOPeHYxofEF7LlGuIC5rk7gnczuwodMrf08QxeJctnzwR45VlG8Qea88quhO4V+7ze2Ja0LTboR+MUS/oh3cqExyossxRw+yvCyKkYkRspan/I9PaIjPljqC/4Luk+FXcO4F0u8Mj3xVNFC8HC7TdwxxPNiN0SJ4+fB0MKf9nLal4VuREMZcXUY0329fWgdokkz4gR+WnroY6GUx0q1uublcGkLk9M4NnQaHxdO9FLV0Y3ko6PBB1g8nSNxdtojBds3ptS2Nuyy9C2Glj4w93b+xk1b1nZW7B7Gq2UipoFnlwC0zERdVDjED3Hwbfg+n7njDNqqMkLsM+zsp6Pxr6diZWgJgV/7KLFPYmmPvFCLbyVggXhkuDydzv8hSqQ9ibcw4StIVSrvele7q+3TsvUxJjlQv+KuNpaskz8uPCNhbRtYF3KDb1rngA+nUTFtktxeSTbgEcyaa3we75hl8jIiwIOS08mipB63anwpMUTAO2OtNgSlt938EiA6yV8XVM5RlUhm4BqgrwOfYZ9FANqpnFsfDDbjk27s4s4zGicAOAYCqqdqgNa0hx6GCLcHZ1Olg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
