---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgA1J++J/vN7sej0A8Q6TWqCz705yBAwD22e0rCfNdvuyOJXuoDH42zc4zxaCP5uuGvY6VRJAMDNLHusHhnl2V+fVIH8YrBmR/qfJd7E/WRVE0ngOqaaT+6J2j3OUWvNNgJlruvL/6924zorpWNr4uVTKXgLCJQh+/QZi2KFPNDQzltTlUlGbT6mjap2Hoo7eGIqaEUSkbJuNONLUQLC4nq9p8GwvH3o/omstIUf1MahoKoHHIc1sMLMHykHDnUuMKF8zAuX3SPhZOTJirsp6Z1vxtZAr4qxBX2FzM7NoirNFwmt/tFJhYijMtGQO5QFGdUUUDD13UiI655dxHVZtr5rsNiJm7Z3rj0OugoCHRpp0p85Xgh8yLMs/dJnH4irK4Zv3YVASDWbHzh6WAFAxwGMNeNfs3/uUE6Tu2xThO2qroEDJ33LndHxgiQqlntZskHymwf3+yWNZCkb+p53zDGhtQTDmA02XTOAxo6arNRoij9LZivEHtcTZQR5yKkWGa20OVafEvwQdtFN/h0avPHX6OIoct90Z0pQhgjeQufRnuymc0qZj4c65XLcMl9GjTzTnRhCk0DU2IYZIdDS5UasX14mI9ZLgLOljT2pGz+clegPXDCWsPoXJVsyd1A7PBiYesvcBYpJqlz9a49TauH8Yq1tiWPOLDPq8uMKqbWgU12RfDSMlkPp2eUjX2UqvK3aodtvcrhv9CWIVcIWRqt1Fqm+IEYXM7ihu2PXIBhxGsNtb6OKUfAGnluQjTAJDQXfBpbxaQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
