---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCQtIkSiljqkWrgroS545OMLsV2ACJWzP2Vju2wXvH1u/G2edtU8MGzz+qrSNBhvYuMx1YHuLfQBVxcT9rwOxQ1WyAI1H5i09jJs8OMMMBW/UO9Q0boFttnk3JIt0V3IG+qxf73B427+2N7h/4KynahEzeTdh6qHXVB/8SY7rJVQ23GYNbiV9SbyTl8pYl2j5BPnBuWlQipLB8aAF1YCIF3abQyE7U7fFmOufokbMNAGhufZep7c93OZ/XUlVhO78VU7/7aFhSpA8WeTmtg3+ccRQL/lBXmVo/WJEh6qlMqCnWvbr+P2UYrhfE0HnoYv9/eRnJjFfvMh6ZSehoyTrBKVcgC3YFuWixTEk1lcQX8UPgVlgRkpEIYmmhasHENjoV/QPys2cNHDLE0J43w/5JMFVbl06rbBJBcZKEiM/zdWkUw9CMAh1HFLaVtYETdKUsHcRkWazPsnouC5xdLpk5w58TW9ep8w0UGQx8jaaKpuJqNQ15TFrCkPiLwz8AzGFZkq7zlntzBmJvs9gFewpN7+SbATaLkpzewWdxTNimclJgN9g01+J0Tj0l94SxtYvzjfH15GpqCmEAbrw55ax5YC/x3vqA/2JbuM9cmV7zPDN4RjAPlr7Xw6ETx6QiOL640oZWfOGj4HwXUYuVBVFQPz6X9HhZ/nzWkVb3qvK7+lRnm1mQJJZe5KKS7haLtiy5P/KVceny4PhTbbmELFn6n+CxxkmCvVA4jiXNs+GHot/vBWq6/ntR1Vx+TkxORC5NLcqGgPg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
