apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgBSHC3jxAsYsHQ2+dKbwRI7hIGMqh4rDPcVNrEDGF/V1rqMJJOmPgJjYqbALOpSxkMuUR0+LmXK/S5/Q3D0ic7qIc9sq7bXBE75vyTFiPGMK6nTfTkQEJOZ7xHukZs9QGcTWMdHp3+PlRT+t2hnQJVpwJUu1D7MxQGFpjeEE5rEzLyPbeNazUvc5TdERzX90U3uW7IWbvdeuj+FN28pFpYZqAcYvuuOMgTE0dBTv3rjyhxFNsyDKeDcgL1txuSVFKQL8HjH02eDjsvpHpGL/Fwec+J0dq5EV0h66DLmIwqEo+mKrOqdK2q0+/BB8/v8rg2XjqKt6MI9W1xMuyfPvZhAHIkNAXIl8kK8Dyzux6d2HXlwhcXTjqJ3dVXyErzqhECO4cYffWc2rM28KZO/kRp/wvy5hHyK/VscqAQ/UGUMBkL1vGT4CuhacLi8PtbTwHbl2mTnSECZb627Psmosm//0BvFVEspo49ZmKwSyumWae99OjK7foA3lT0s24dwR5b/frRIMYmLv8qj2PjkTAbrdODJW0YKi7QiaHVc4PytN4APoVYWpOxJh+l40UKdRonrm12stt81QgiitHgxeUA+8RYUXfX+D8cB8nq13p1DrvZXg97dta7zO8KCShIuSC2TCHS8R1xnxVaMFgEkpcSAr44nmqZgnZ9YPPrQFtuPB7XamVwCD4WZCQgP42/6ZcEOd0NtJMu2xnmSL4VyCrfeMIoiP+gQ9KiIHh9WZ9e2pPpVRUA73dUUOjMpgNeTWdS2ONe9fQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
