apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser-secret
  namespace: cloudnative-pg
spec:
  encryptedData:
    username: REPLACE_ME
    password: REPLACE_ME
  template:
    metadata:
      name: postgres-superuser-secret
      namespace: cloudnative-pg
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-db-secret
  namespace: cloudnative-pg
spec:
  encryptedData:
    username: REPLACE_ME
    password: REPLACE_ME
  template:
    metadata:
      name: demo-db-secret
      namespace: cloudnative-pg
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-s3-credentials
  namespace: cloudnative-pg
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: REPLACE_ME
    AWS_SECRET_ACCESS_KEY: REPLACE_ME
  template:
    metadata:
      name: cnpg-s3-credentials
      namespace: cloudnative-pg
