apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smbcreds
  namespace: csi-driver-smb
spec:
  encryptedData:
    username: REPLACE_ME
    password: REPLACE_ME
  template:
    metadata:
      name: smbcreds
      namespace: csi-driver-smb
