apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smbcreds
  namespace: csi-driver-smb
spec:
  encryptedData:
    password: AgAL474Tz21JojVjsc6Bnc1+phgyDDLAZTwoOpYE8AUdLaPNni4ZlBCF2nmhsfooIYRMQ7keOFtmK/1pg8bvirfQh5ZOGalnHDWewMyelM/yMg/nA7vzlDYJNeA3N8se9TXB5wZ1ycRVcttj+J3h6p96uI97ffl6sH5x2/IUG5jzsgj5HVfhVAYwzccb4DCGGEdJhw0qIFWLRef+oAZG2sYbVVX1t5TMae7/FCn/REgKa1Hj0jvZnaCo0L5BEQNDDBlGeivDuTVXFd4tPFVJgs1X7tRq4Sq72ttAz6Vsf/mejqOu0BxJXfQplxTKrfc8BYL2DcY5S3mQ4Th5v7lCcVRNYcW7Mw5S7MXf+1vishzy7b9183M71WDkfXFeKmiBe9X+YXVPxAyC/P2EcYTsz7FYA+YTTenZDsQEXy1/XieqC3e9axbN4biGQLM2lfp3RcihGIRUolQT6Q6ewmD7A10LfuGP+2Lbg+KQ95LyHWllAyeXj4FX1jvruYQdUP4AZnsUusEtQvntOYqwohTX1dXM5+mr3oIwoCRiJN8BSD5G2D5b7rr4CI7oC9kFh4G2ujGIdgM2oNm6RpSD/ortYYOrQiuSS14uBIzZE9A2YzIOgsySNZW+ox+Adwp8llugjy9vKPy1p6oKqtCZNZFS/rdegw7WgLX9NVMtOXh7RTejeohJhTw/6d1JtKcP3QKCedizGDxZgMgB
    username: AgCApmQ6rw9L94eCtb+GELTzBgBf2v3Skmf3M4vr73lyifkXCQeWaK/3kl89gwOx3sXl/UsurxgSDnjvVSxMF2KZ8gPRLut2MyFG86ggBOCrcYD6OHidyGvNc8W138U5FeKKfmTXQJP1glUrGyL41g7cCxlVkND95FDgNDOSnVKuWYQLHbtsNXGGjbtPJBzZvpLsLdqkSmTWCMI28OKIUlVpLKeNYTy6BMynezGGubgTFIEfVx/Bk47MUsZn6edaQwN+b8gXqfZKJXFbmTCum0vp3LVMnBUMCVNZeZdlvZRI3/lT70tfjIuCoWzkuLaMKzUeC8s+cx1qufU0/TjrBAYkQfL0mLvaqJcUnOhBY1e6Pm3ytGz7VUqWomOZRvpHT8Yc1Ao6agpeAct0PguFOeFqH8gS7Qhn0siblk0OdevNuJxgSn3w9+Aqnw5SzVuGsdxww6x/N5q8Hm8m+kr4Ot226Ir0dR+KzdlUAL1OjoMg9aU15oCG3SEYGCwf4XQBZb2GgAHkn2SxbwPCwCwvJfHgMmfC/RO3cnwXF4x7xUSnf5I7Cn8U9lo/yZWolKPSbCf95Oc7ioBg/TvQNIxbZSj7g62p8CBPuxCWEEAlh8lXc5KsdYzQgyTcI4g9EOsu6QEeqhu/I/f8fomW9dFDZ7tqmnl1EC2L0QDdOgnqv5Y3ZFdjocX6EPAoYvlITjyXhQg0HhM=
  template:
    metadata:
      creationTimestamp: null
      name: smbcreds
      namespace: csi-driver-smb
