apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smbcreds
  namespace: csi-driver-smb
spec:
  encryptedData:
    password: AgALLx9o1EV6QiJsK+U7bl0m0zbphldgTG6x5GNeS2O+vDQPe/OjPq0/R6fd/iGwrcgPmA+fvaOTqgtpEvfD1nlvOiCJPCeR3clVOttVgFlWMEjzptx1S+3t7pILofV7+m20hvBk1b5bI9bqI54b3yYCQno64fJe3psSBKd1O0voYo61aFZhAbGnHzSRx2pIIFEv8CFUpXV6+Poq/iDp2mRepOlEyXyrdwT9JyEJHKeb88Eu5J4T+bv7U+4D8rlkTd1nWpHStI56Shud+6Lna48dGrEXcEHVMGwL756Y5MPDahMVupS5wrhzVi+l/LCi62IYWyXtFJH2pG0iP9HdyC0S3gCZ+6YSaXu+kLWYNvDxzOmT5RsJUMaOtw9154S6AMn5HYp57S5cuiU5/jTWIlRRcUQiDhkF4vg12CR0XfRlVgXZzjwlpiObd5bUnd16KVZeGDPCBDAY6UD/tbgGfB7AIKMGMrw3fhwaIcUek22Gci7ygUcuWzW2q24f4ma5UlftxIccSrRUhUQNLpTKbLsu7YZQVW18IxJxQNziqHFffFqYRxanMe5R4CJJ2r+Z/RsuZwB7pZNcM5T24k9kenENU7CUwqkcdOb7kWDvJQRKSGZCed+U2PSHK18cV3bVeON9kWxekeTw3Qh+CO87MI34hJiSl8f0PTVuMw4ZQfHiw6NpLHgdu5aDfcZExu8LZib8+VFXuJ4G
    username: AgDR0NyyUz/QSQPcxcJAEnMvH5Vs4jgPXBnw0Mtxon73Er2xY/8m/dHKOzepFIVUYJOaFPkz/593KGqemaKPXPsjv133A/ZEzjJeRT43wTwMDmg8ly1V1EP0n+UDcf7lHuMuS1FJ7R+Ayy/mWdyVnEIV77gmdtjgfZE4O+RmjXbl0Tam41a+sqEQS3kRuweixZLsiqWa8j4UuVxqm1kCjVvCa/woiM+WCAJBOIbqcjOeEHONrEbFiwEhvrJsal2ztPNqH1hO0dWqiBU9ZvXt7JW34JDzqNrVFNR+mS1Q50qIHA0hrRZ8ypq6RENzXGVcSbX9DprmMknD09gwYfAwKSqixTP0/ZEyNsadJmgk3f8m930cTX3RKTooBLm15M/5flpM3O3WhhKAM8l6fmUIjLbfYiKLqywF7KoA1XzDOlWj0gnrG7z2qIOm4cdWJ7J3uildRV8T20mb8s5ZZizMoA7KvOGAUrOtbcjn8WUbDQqi8RoDc0pmEfAxY2F1zy3F6oKH9NXQlZzMklcT5UdjYocHZdIIcakzOt7xo9K9qYwoLnF509TtWTctua/BMx7VZxZlMH9pXbBhnpXs9MmTqGZG9pzhEA0fqfc+U9bE9IzKudyq/AuWrs2DGIy1LOlPeUMqWGcaBWM0sCJcLKDkKpE6ClY3XzjIhh7iH+fDefun8rOmdUH2eO2eRaROd1ybbhDJZWw=
  template:
    metadata:
      creationTimestamp: null
      name: smbcreds
      namespace: csi-driver-smb
