apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-data
  namespace: copyparty
  labels:
    app: copyparty
    backup: "daily"
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 20Gi
  storageClassName: longhorn
