apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-media
  namespace: copyparty
  labels:
    app: copyparty
    backup: "daily"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
