# CNPG bootstrap secret — lives in cloudnative-pg namespace.
# Cluster initdb uses this to create the 'backstage' database owned by 'backstage'.
#
# Regenerate:
#   kubectl create secret generic backstage-app-secret \
#     --namespace cloudnative-pg \
#     --from-literal=username=backstage \
#     --from-literal=password=<PASSWORD> \
#     --dry-run=client -o yaml | \
#     kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-app-secret
  namespace: cloudnative-pg
spec:
  encryptedData:
    username: AgBYyvuz7xz22Dpi8qX4FzCUci82Fr6hhVf1lvzx5E5LDrNwNtb5MdEhEm0sd7Kn60MesGLAanr24WkuhAuCXk32DDqlnNmXosJH/WmSQfOvJ1uyO6i/vOoSCYKjwRv4C92OGfwOnlIaseXKjJSekA6qb659ZCYNVhNupSM5vYVw425EgHN2Vv9OQYRCaLTKyEhqGmbFAxaUgXfWeOFcZ+wK4seBOhfx1vVXlTsN+krsyrvcEJ61AbKKt0ANageYn+ZA7kA3m8JtA8uPE/aQsOiJixrNP/OLYoFWPUf1kFqnXyBVhwrofcODivErEC/j/bzzH3SZftiOTsaPXT0NOQHvPnwB9guAB8ZmUOzFmzM1WOM2QFyhzRfvZhnHHB+jXF62uNanYHzW8sJVW6q6t2OYvX0yyEn8aC0qd0zdnv8CnIw8eHow8z/7RluepM6t5VraogYEvxoLzGxQCEIfAJbjxDbuaP9EszDgjJKUH+RG0efUFaq6EHuHrnjHwBiHiBb2A4yjNirFY71GRch03hC7+yUf0uBcundsQRNWDKoC4KBbh7lk2AbPiJ4G77s3dbuWxRNthMqcZnSmK87HM6VK+rTQoNWOeF8vLGRKhVXudSmqYis7xyMLiGnxbRX3PDj1RO6y8U9nzuWO2C2T8qAZZti/DWPEE6VjwpfYU54b9tClr65/6PpP6zTTTQr2tAt0rYWoDpK78C8=
    password: AgCCds/+qiva2VjCCLG5Krmo+vkUAnP/kxj8uylrMdJIm+OR5qSD3ftUY2INz/IrEhmB1xkMSeZ3jrTpj32RoAgtQ9daKleqPHz11ilX93vsBfDltNVf0DeenidTF6KCq/FhZfoPC2U+vELlfGqSTEAV3uNzhzNg8c6+el9DdN8t3BVGXkzlxFz/BlW3I/OktZ/HlDEKOAGREs33I/NdXz5PgYzSO0iTnS4VuSZsGAQeSnqd9S8c93jq4MTerjtAwPknbCR9uPFjmb7Mv85QcSYhvDHSFncxnhY/u5dzmMhfbXyCQ3R3uSa8oYbW7LfTWPMyBdpjCpZ9njx+/QJrvNov8ill4uWePR4ZRADrc2QGdzWC8BYStGIIaamswxZYWH4heUUB14Rt3BkTDeD6PjIlGLdkegljKXWK9lZIryLV0WQ8gaT3o+OqFxytoWKTXEanr1vMSeRGyYSKpRueH14G5IJwj6QVPR1arHbyDFaj9cKYQRvJeAhQ/RU4YjpJJRwyXIchXDnTf+5Dxr89vDz2UtTPzY6IxZnP3i1Yz2cNRTh1AeWrghz6OCJx4RJKVgUUM2noebXj/MeijNzmeiOPi1vpDY5+x8hYcimk4N4Qxkf3lhrG4UMkoOUMjEYNYggQ50rDnb/wx0OUHzobtrPRXNr3pndw80LkGZjIoC7Nt3sNDvTGqME+gechwkc1t0dNoDOiimMdqpIG90g4iEjme/RL42vCZzi171vnogYNeQ==
  template:
    metadata:
      name: backstage-app-secret
      namespace: cloudnative-pg
