apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  namespace: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: development
    backup: "daily"
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # dataSourceRef is added dynamically by Kyverno if a backup exists
