tempo:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo
        endpoint: 192.168.100.2:30293
        insecure: true
        forcepathstyle: true
  retention: 72h
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  livenessProbe:
    httpGet:
      path: /ready
      port: 3200
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 6
  extraEnvFrom:
  - secretRef:
      name: tempo-s3-credentials
