apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-service-data
  namespace: platform
  labels:
    backup: daily
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
