apiVersion: v1
kind: Service
metadata:
  name: platform-audit-service
  namespace: platform
spec:
  selector:
    app: platform-audit-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
