apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep-secret
  namespace: karakeep
spec:
  encryptedData:
    NEXTAUTH_SECRET: REPLACE_ME
    MEILI_MASTER_KEY: REPLACE_ME
    WEBHOOK_SECRET: REPLACE_ME
    NEXTAUTH_PUBLIC_SECRET: REPLACE_ME
  template:
    metadata:
      name: karakeep-secret
      namespace: karakeep
