apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: infrastructure
  revisionHistoryLimit: 3
  source:
    repoURL: https://github.com/pboyd-oss/talos-argocd-proxmox.git
    targetRevision: main
    path: infrastructure/database/cloudnative-pg/cloudnative-pg-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
