apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: paperless-ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
      annotations:
        instrumentation.opentelemetry.io/inject-java: "opentelemetry/default"
    spec:
      containers:
        - name: tika
          image: apache/tika:latest@sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9998
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: paperless-ngx
spec:
  selector:
    app: tika
  ports:
    - name: http
      port: 9998
      targetPort: 9998
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  namespace: paperless-ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
      annotations:
        instrumentation.opentelemetry.io/inject-go: "opentelemetry/default"
    spec:
      containers:
        - name: gotenberg
          image: gotenberg/gotenberg:8
          imagePullPolicy: IfNotPresent
          command:
            - gotenberg
            - --chromium-disable-javascript=true
            - --chromium-allow-list=file:///tmp/.*
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  namespace: paperless-ngx
spec:
  selector:
    app: gotenberg
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
