pipeline {
    agent {
        kubernetes {
            inheritFrom 'skaffold'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Deploy') {
            steps {
                container('skaffold') {
                    sh 'skaffold apply my-apps/development/jenkins-lab/jobs/deploy-dummy-nginx/manifests/dummy-nginx.yaml'
                }
            }
        }
    }
}
