---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgCUlz+093u4uebrRXiWNqPiv8OdCidcNOIlSN97qDEvK0g1cuGqX4CsVDD6c3qh8jHHtGA+QFvRHdy1gxGhHbkIrPkfcSSidqpp9XY1kX9dipCEbQ9dymB4MpEUjr1Nd6qU3E8Yk9/ZyDKrCk3MLIaiTPsaD+3CAPqAmMywN9hKHxhVBNGuuAR9nGhi493RrpwSF2g78JnyXBc5UK/I9VHgj2rg1OZN9CdAZ1dAT8cNY0LM7RMVLl5+ZBpmC2SB3jBdt6xtSOnucCf4b9UW3HsTwbgLW3D7306Egi2rS7EGE48HgLTllHODNCyKjt3J9fdi+oNxkV/2twhKXo5STs14aQ4Y878BqQ7UUposKMbzHoadJegKZzknwsZh0GP6aqqKF4+LiLR1mesT9ouhvqUwWx6fWMhhstSOXpcPPm4vL925L3LeRcsNrKyhab01FmOag088hiTm9SsTnMMfXG2GN7mOsyKMUrgGpLZe10Msy9Q5Cz0jdrHpYS4JTqgj5ZtcctOohsiJvlxnyhqZF6umf+G/uyPCHaeGMoCwQuxctGuYmTmX3nzxiOYEAgYwdH9VMkNY7kbNjdzmgQahnLRpSI8dosvRf1wOJy8QwXmrFQET5rfbmttIjp3XUvUTu715FPjKQ5YwdjAPcRvR79yOqDmfal94YKDnXvQ4TD/F1bH5c1N1NtVMN2VxU5lzKCGYJlphqX3H6Oxj7GEjXOJbupWXJ4MnzREQiP7Df1yfi239llj2mwx7VQ5/9SpbcfF6qCvf64dp65iDDBxVCWWh
  template:
    metadata:
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
