apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: jellyfin
  labels:
    app: jellyfin
    type: config
    backup: "daily"
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # dataSourceRef is added dynamically by Kyverno if a backup exists

