apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopia-repository
  namespace: volsync-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: kopia-repository-volsync
