apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: volsync-kopia-template
  namespace: volsync-system
spec:
  encryptedData:
    KOPIA_PASSWORD: REPLACE_ME
    KOPIA_REPOSITORY: REPLACE_ME
    KOPIA_FS_PATH: REPLACE_ME
  template:
    metadata:
      name: volsync-kopia-template
      namespace: volsync-system
