# CNPG bootstrap secret — lives in cloudnative-pg namespace.
# Cluster initdb uses this to create the 'registry' database owned by 'harbor'.
#
# Regenerate:
#   kubectl create secret generic harbor-app-secret \
#     --namespace cloudnative-pg \
#     --from-literal=username=harbor \
#     --from-literal=password=<PASSWORD> \
#     --dry-run=client -o yaml | \
#     kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-app-secret
  namespace: cloudnative-pg
spec:
  encryptedData:
    username: AgAxAP4CjIEsDjTvO+PKccCDFLHTj444/ePKcpkAIHGk2uXyo/Rpg/dl5mSX8Bo352kX3cvf/K1t81wLfNkUPc7hqPRpEVncRRAmeM4p2aA40O1DP/qfh+Cjgkbg3ZTbQdgERUIudmWUwbGWZCbPnBdnZM6eokh/go+nqpdnkAMmBhXWwDvKGrI0VyafCcESMAwjK0W+r889JgcOrduZCgr5DpcCnEof1k/VDiz6mBNwj4a/cgnMWtulE4Vt37R4bHdJHQsMaCDFJl1Tt4r5atuA6W7nEJLwuH3rqqDjmIjL08hWA9aTBx9Sls1liS+qP1KtUKUQXyfh+EVYo9jcl8xkl7HkRq9iV86mp9fEPlPyHyxYCMizdezgii1ftsg26RctEm66v0iDXI67XcBG5b8ViGFVdl7pxUVo7a6sKc1/R5t0YnasYj6xQGpiIaAxUEF+45ItZPc1GX68HfaY2f3MiBFZi08pWmPZoxgZLpGDB41zv8GTfEDea+xToCRKtgLx8XvA9wODRT0AlSmPtxN0RdHvBazFt2WSZxnAFMpIgX57IQwuJSlOkz0gOKcNDHZl0cmrzte9VGSDC8Ntu85tu4rHQYQs67/zgB4i8Bm2RlPW0v3z8FHrqfTfruFWCW1SfRbAHx1mDHqxiL9V9b8enB9DwAWn4EPRGR2oQfQKkZc6dz4BUhHALmAyaHbQmWg/OTG+UOY=
    password: AgDHSLBhuCnnVvKzeZopB83rU5GDyaEhR3MmXd7KR9Hno4Tk3cAycCU4VzTH/qJd42fVzPJGSqgX343javXiyjz8TUYwtWx2zRWgLPrTTJSnVAxsvKpII60SKW/DUefzN96dXsPBJupR1QiYONOe5Wk6UBShUHJUufCvO2QXOpEYxY27amlWSW4MUxy2SxV7qFNhr7RtPCn51mcDoGBX4Vf+dyK23Fto58XIxCv29B0TPKDzXQ3fDjRISFolYMj0VrEn09rNw96KKTAAK3sJjsEdRTPHr54EMvmk5u5YytmNjJDf3nb9cRZ19+rb8WWad2jG4VNfCicdYeCQxKtJP9gM53cofpakfBpb0nyv/DZp2NKQfQXkBEq4opZJ9VAwQJ0XRP0zMdgakpIR+iA6A+2dBvX6bl5ZgmzN21REjVJiL+JCgwZd8W995Ztdm/KZK2s9It1llWE2j3FRhWr4B9AYHhGGljTTYTjmT8YBXWVx4V4btbAEHtV8Sg4TPraS3OuOpHszNmwTiZE/J/uuf7X+1Zqs6Mo7Q80/Plr4h0DZaK4NOXkTfmrSonLbGiwIfoa8GUhcfZHjHFVa8dCoqUGMV/GJ1kTG+qY4HEUkgi0muiNTnvyDXspGBFTlJ6vIjDZmfzqhEF7EgXbivO5y1gYwBQWjWHqBbbmhIt1P42uqzPJsosF9fhwE5qmmxXe05E8U9tS6ZrAJk+MSsiOEjw6yJ+UmEbYwXRNJwVqtnB7eYw==
  template:
    metadata:
      name: harbor-app-secret
      namespace: cloudnative-pg
