apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: temporal-db-secret
  namespace: temporal
spec:
  encryptedData:
    password: REPLACE_ME
  template:
    metadata:
      name: temporal-db-secret
      namespace: temporal
