apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAfC+teOq9rKOLIIGEuUBgkhNIZWN2X9Nr2uoCj6KiJMSnWQJH+bs4xMZMGTP9yMrKSUcwN2ExaEXKHlQFkYAKN0on3UMZLIm6sP3G7X4uTzNWwUWdvv1Q6HlTeQ0UM09kSV9jIj2TtnL9QUMgNTIi7ZqR77kKJGFb/i1sXlvQFCy+7DFxfwuj6RM6Py8Q6Dt6OnVa2Pt/IbEjmF/vIcCHb+v6pQzBX/0qtgFEVdiOYxITSTAQ1vAl8UvisNJx1mE7SGo+M7NHxsmlBlf33mQYyoBsEvd/3rjPq7sfUEg5MM8IS+feFqV310JOmPZ9iikFFtwCOpCV4gf6+VjPLKAxpxHPslnYfrTZFtojlxktqKsAZC02wUADtbTXVfZesZavXh/9QXSj6pd1wPRvQ2BhnIlGLZOlPBKnF9p/3Za4/szSCpblJx6CIMY1mOePm88TVr+WkughVi4/1wzE50OaedSaPf9QEi8DH2RyrKpwur5io3wPCNhEqh0H8l01ntEGsPU9QoaGFnEBz97DB4xqsVfi63RHL7A8NNccMuXmThSBZPIjUURqyUNspAH2FMyA2zsop9lgEMffbNibRJvgNTdmnQ+3S6apkO40u/LwG87WQxBiZajCzsAl4KUCKLSaO/HMTxyJM/ZU1+S7cgk9zK+C2/mdn1GO+75BaVje911z1Qmx0lyxsoXxlctr7wBAJm0h0101t++/wRv9U06yDhlRDymx8Qa9hmhr1GsveiPMpoGQRQAYIywp6wUJa36gEj0VXLnvHIN12yTz8S0a2aan4MoNhaaKuiRNfTF1F+qxpuYA8fU6tFToI5y+ht3TtSr2oRan8CNY95b9dbEdzkzKqqmZY/VVwG8yCa56LBkJe4hNPqiULjBW9MIOTj6pKV6otKczQmJCsIwlw30buYgzMCatD
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
