---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgACE9HEATt+bUt+5UHWHaCAAZksW2Xwfuxmfnunt7ds4Nj8OZI2PWnMOpEs9jzPf18LPjLKgsMAA+1n1uYZ/fIBgLNoTwnoe7UEzt5d/77DGAFOqW8mK6etiqLDKZ1sCKKAPEheo+aaq6vsJauFnV5be90RXR/fyBf26YUuWGcLosnOZGRh+5yf2htUZnxnQ5ebgnF0tagINaHOyB56aV9FXtYcUYXMTEceFfXMLuX7E25od6xUWGWe0RRMEJsnUyu4pzVf5BYBWq+rl1Fov7Fc1UAnMAmchjcevp74ycbM+nbEQ/OpMyeQu90C6OwgxSrok8yNGn+a8jK/L0AKv5BP9W6tyaVe7zizXHty9/AIwlPmJlE5kW0erKCMtTOZWykXEcLDkKiedxrdJ2/3shCMHJJhHmfmV0ehUABersp9Ru+fcD01TbohHezkCiMGUzMQIWyq4mBWNPaENHV4pgJkkZc3Gxjk1ULfN1OaBB40XJluiYbqLAWC62Yoe6fKnfZMac3n7tdD/m1hJavlC0rAZKg/uJNFdzUkAwGjqQvkk7fym43JXdYvudqp98MsVl/RAc7dzc/cIfatc6+p4WimUErMawzYMXE7O1L4cE1P9Gc4BAKDA+llMOjEJXwfQ64GltwoDX/96bxMz/HreNEpQ+tLB4IhVgXE27DNVmj3NkED2asmweSL9q+3jIPRfpceOtrMDN1IenZ5C9zPJyvQ1s9ByDgjTN4n4GVrhVsvEcrC31w+xN0zC1l8CX1XEwB2Ssp4XkueNFcJvMr3aY+a2pdjdejZJ+qqckApJFMd+P9mHIDpd3XHptT4ChxHq5HgmD8yFoVsuJMCyDb1QsEVHH16qcoD/fQiXXKBAFmC9TZk3dvT3S2IwVFn2OEP6x2EoP3tW/MQmHmVEK0z48dA6cYfZ5juvO31fCn2X6+fH13FLqRM35k+Oiuv
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
