---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgASomEpktrfyL52rzN8AmGgJLsZtsIFQFhFPtfgrZZs0WrZaPh10iTLg+/rMQj3SAYJhLMnpzEEkvtD3d1AbCAb67qk81TZW6pod+Qx/aVZaTdjRFsaM+wTTjbKoII7FxQCkWEAR9FGs5j28nZ5uRmOv1mVdBIBhycRAFqpHpmQWbKVJUY7hTvY5Xq5t6Ksw4ksSvtXIGyb2zstaLBPzxxO7TNNZhZPAqGYt7Xyve2AbKOrU190FxxrYyMiA2qZe64RFWAV66qQvcpgZ57C9GrQ29VtSjD3RpLE3r3l3BA4+GqSx4GCdS2/qiMWwGdzAYRZaJyxXBga507uDdsoLZNc5oIg9V3una/q8JqBICBFJak7HUtkFW2jbD+hUseWPpO2cWOtejugiVpcXoJh/+emAHGcX/DVQXNBKZHSkN1KZXYflARcg/8ns6z1OBQTMUxmWWl48OJm/JPaNlsPJy7LQWDe3xt9uzy5g+Ufp3Zzw7ZHNxO7NLsPl/Lwa9d8t+eGG1DObA7sW4Y4BCCXmRF6Q2grZCIlmTSOqcebgqKh1uP1Eqb+q8d+l5XoV+2XponWoBzfhzmj2ud+Vf54HZMp4objdua1UHhq4WruUARWy9xl6X5mgUq6vqt0y/8U1NaG2RVQquDux1nb5mei9K0EVXqmLxnwgjOUESRbjZeEL8SahWMtLbUD0OVZWbv1PDmrDx0Enreq7166YqBSnZ7Lqo+pD71oEj8xkYEbDzyG2RA1LTU9ztd34oOHvCWjZoEtXlhWDV5iverjcd8N7c6zTgK5byJF5GplcOVh2wv/r73tdlRbFSIzzOHUdjEL44WMQGIl9AOSO/UKTgf4ZkFecI4s8NV9muBXrcIgKzf7DqJFNrbCJ71h9s+f9FzA6i8fIdHkLkVAX7jDZXGcSqRCMRThmLclTvrxal2YOZJY/btorbHga2AIf2NM
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
