apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: jenkins
spec:
  configurationAsCode:
    configurations:
      - name: jenkins-casc
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.555.1-lts
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1500m
            memory: 2Gi
        env:
          - name: JAVA_OPTS
            value: "-Xmx1024m -Xms256m"
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
    plugins:
      - name: kubernetes
        version: 4423.vb_59f230b_ce53
      - name: workflow-job
        version: 1581.ve4b_d0db_fcb_b_b_
      - name: workflow-aggregator
        version: 608.v67378e9d3db_1
      - name: git
        version: 5.10.1
      - name: job-dsl
        version: "3654.vdf58f53e2d15"
      - name: configuration-as-code
        version: 2053.vb_0da_47381a_25
      - name: kubernetes-credentials-provider
        version: 1.303.vdfcf47fb_b_fef
    volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-home
  seedJobs:
    - id: seed-job
      description: "Load all pipeline definitions from repo"
      repositoryBranch: main
      repositoryUrl: https://github.com/pboyd-oss/talos-argocd-proxmox.git
      targets: "my-apps/development/jenkins/jobs/**/*.groovy"
      credentialType: noCredentials


  basePlugins:
  - name: kubernetes
    version: 4423.vb_59f230b_ce53
  - name: workflow-job
    version: 1581.ve4b_d0db_fcb_b_b_
  - name: workflow-aggregator
    version: 608.v67378e9d3db_1
  - name: git
    version: 5.10.1
  - name: job-dsl
    version: "3654.vdf58f53e2d15"
  - name: configuration-as-code
    version: 2053.vb_0da_47381a_25
  - name: kubernetes-credentials-provider
    version: 1.303.vdfcf47fb_b_fef
