---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: token-service-jenkins-creds
  namespace: token-service
spec:
  encryptedData:
    token: AgA/ocQtSpKBpoaYcx8o/cwvwwzeQFP10AA43TFHOe+CttkVTR6BlBaANRnFf/1PWTeirsW1Kw28NIlAtewclXSeAgW5NaPzj03cMTM8u8MleXSSihR5KQuZteCs7ZFU5w7lan8adh+qi3FEuzYBDLz+49TvvH7QT7bBK9Uy1EcW+F0hxJdir7pAwouPmTSTS4c0b/31JxYWX5o1CPS1mPMRDdH68MWOISEquWkchMXNo0KhwmNF8Lb+Um2vMpFqmICdaU9W8dcw5xZxwYLSHR/PRztF12F0LX9mK6Xa49whg4793ShHyRDFgWWbPectbFkfEowW9FMXoT6VvlbhA8NUS2HJvc/LVBOwrTW8ZLwhPzRChqcya4cL13IThYgDXvYy0wyW7P9hN6abGvQuBFLHVEwUGr7h6surFN1TdGM+DCNoTrFp//VyTzidtyObLO6gv9n9ranvtbBdFy4/83bZyN9kgPwLYRkQxtkIh1tvY3oew7wctga+vmhxnpeevGZD2vsE7kNAh2idw71AFdkT5MemPUPuwE0086Q6vXSUwhTA5MFP3BGCW5PSLx3MhBIsbfJyUxPjvUQk5sLDEHRzGi06oK8aiM/1befBg2etUCNW3m2FoMI+GXJUpQghSXlAQZxTnC3Z8rX32A2SLg1Es1H3H3DT4qGzDjrcjfp7CJunuWKK1ZkK2b0lsolTpA+/Z4EH0nspkIFEMVqicdl+ofYm3BcZK6V+ctClTK6imaQd
  template:
    metadata:
      name: token-service-jenkins-creds
      namespace: token-service
