---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: token-service-jenkins-creds
  namespace: platform
spec:
  encryptedData:
    api-token: AgAqCLhJbkcSKH82V9iw7k6Yz3/XEpo/6GQDbS2KeUaVexaL+dYGQxiPKubPek2vvKiAh7m2oS/xPUvPfHj7p1o1hcShyKMuoags4dA0AQJ5EO4dnLi6lnoDHMcveCxYlTzAX3kUtawoFFv+GvEyKMMwb10zlS3Si62I3vjM79VLI8DIUdxjpOTXXoFJXNeO7jPC+y5Xg09lh+pFjJ/ktB7TX97mp3BCvFVggMmGUpnqzgS2+xbRxwsAFjZ9hWN6Y0wB/0P/AR8a5ywWAzsOaQ1/sFdrP7C6ZtpcycGdIBRomLyjMxfP0Lw65NQ9jYQ9f/tVkRHmRKO8xqwRCsEu/GSYGYl8c0FpK8FRTykxFJIskFs2YiIQ516ycdKLRTTH5OLHz4KE9e6WEVDkqhKMpTubDcKQWGLQP8mXGbsTpWRtEUX0HyL71zCfJ6hLSw76yOxk9HG/y2D0bTy9RFTRbKQUatuu9IASwRWks2KT+sQZsvy4wVClh0f3SuBMTLwhu49IkEjr1NhPRj29zW84vdJFCqfxaBk2wXGnVKh22j+V3O2TZ1PrWtfvG3djzz1l8KHvO8EOIXqWPakyP9wYq0p54Jt3517YziiElTFxMMuO15koJIVumvyQaLITFf+HJ0QipA4+HvkaeBEOrxTGlauYdgvPFd89GbvaPMa4hYCPgC4JhVbwJveo2t7TJF61qM2q2QboTHYnQenmfITigyk7LKFYTRa51M/39iL79AOnxV81GyF3RmoR
  template:
    metadata:
      name: token-service-jenkins-creds
      namespace: platform
