---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-db-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgAdTkDcp8FL72mXziQYHeBQ/BNZ+kYFjJSh6px2eyCJR1c3s2VA/7sQpNmV5M61LQ1x2Gxh3y5Bk8ItHMwKqLDFnqTlikvB3Fi9aIoOqX1dE6NC2RDH9mHAuwGeIdBlaMonUXp1I48PXrfpDchWc1IGv5lFQw2K0Wiee/lbjDGQwlK/VTKlh2WGqXu45Ud37wGa29KjFLxqD/pqPUacPnOMzP5x/32ezXAvt8I7QAi/bSOoy2ImjotayGXka497fT726fMhl1xqsMY1G56/FNEflIPFsXEl//dzk1BzMq+cF/ub22iZuGquzzuakig0MIFImCxc7Pzldta/ocqfDU0GnydrJ0QwvG4Ppic5b2sf2Xnz834FVLM9+cOwl+GrHDlQwk65FtCuHigXFD2tlcv1YRneNEf4021WE3PoMGnwGD1weEQof6bFbLZZg8evFxjpTm6hkDpq83UPUCMZQNcS9John+oNUy9j1ahYfy+baxMyNpxVrLryFvx4Hzr5RFV6WXWpeaz3dt9EEtXLL+TRiy0YRpN/xTfwbg8jtSljCRKm1OnWh5kWPf+Ny84eCpYbw6Q5/D8N3T9pEZFJw5wd7N59IuotdW2ItwkLg1wQkCrxAs2gAnDDd+rTvSHuLgWq5iXCpQEQCza/2uG+2qkk9kYCyOtFeIwD/btm2lZPO+OsKTkPQ+uAWy+UMtkFTF31GpIJbgDb
  template:
    metadata:
      name: gitea-db-secret
      namespace: gitea
