apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nvcr-secret
  namespace: gpu-operator
spec:
  encryptedData:
    .dockerconfigjson: REPLACE_ME
  template:
    metadata:
      name: nvcr-secret
      namespace: gpu-operator
    type: kubernetes.io/dockerconfigjson
