apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nvcr-secret
  namespace: gpu-operator
spec:
  encryptedData:
    .dockerconfigjson: AgBo4YabwMUCowwbncW7kgMIrhZhH3/8Az5iNsj63As/Tb8g/oLDzScx/VybLP/KdbTLAZf2JKJT1Hh2rC0FHupjCZggsekvgl9gaT+nBBWT9UTLs1olpMo5OkNZY+GWJczt/wrOoVBAGnV7oMbjdS6ec6VKk2wTp9mHHrgDmijaKlDsmlgbgkE6eja2G1U78qtAjfP6Cd0CFYSCwxOT6E/3Qd/RgeDgfWSRQt5RhfFBg/JkxQvqUHK63qJN1ACJLwigMoFH7MV0HHLrhKjd0CtFY9Ns23fCxhqmD/n2vUmiEBsOUKBzM7YvtqMZN2Mq/A0P7fi5CErnARHW02kJtSrsORN5TbSq9mMobCII2NvL2/MBoQOHSeoZaZg+Cze5Q1w4NcZTJBjQmZ9TrzbcVMyylUf7QgKcI4pLZHH3SQoJborlh9hpjJ0uJLLDkopsYXiBqJSjdLpNDTGRJjr1aFYfZjxQ6Dv3URqxWKy2QOGXCiuWIpE0KVGKeCvHrVjsLSIEv4llross3zA6jm2q3tvGcSac5ZZ1oDyALVoWTLJgXJY3vkFYr+wycM9cRwnhkDisLbyMBaQPhS9e7cfylw0y8EcpyulpBmcqxe/bERDSx39i3Zrgg/Oegdl8MSpOE697lhFIwDXJilPgnJykwbfpt+MuDmViYXTvrZtFWTyk7JAhgAnTi0w8x41s8KBZVoHSECnK6xny5OA0rERgGySDC2w7hNJGE01wEdsIoMmJg9Ux/mYvW1xN9DRnNjtQHyF4vk7cqRwyDueJ5JcHooq9rNe2VHwacaPTSodK+DAsJK5Ma7uPWpTZEeAtpePyIT4LJnntbkAzBF/MbOnc1CWzZ/kzQ70ZjEH5tEjAVcyfgLYEZiZhIQlXeZb5YEM99aZWSPpiw7P2KmgwW97nw7ksQa5zJnpcKEVbRPj1lyTtkqbcEYQzNXm7na5CiolWnH9+7u8QiYs6u+mtvxFMk0+6jywL6pAyHcau4aKvxEnKHaCMyDtaMlTMbga5hRWx79/D8wjvBMMAfKK70RVOdQ==
  template:
    metadata:
      creationTimestamp: null
      name: nvcr-secret
      namespace: gpu-operator
    type: kubernetes.io/dockerconfigjson
