apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pvc-plumber-kopia
  namespace: volsync-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    KOPIA_PASSWORD: AgAeXwtYV+CtPEks6ucgWvxOc7sSc6qXW2eoO8Od8QnES1wfdSVRoXUasiEf24B5lQHXX0OLF8ENRqiTgDS3aIXtucu03JPd1cJYVmuARBg6VLm4EhVxGltHf8Qh/HPzWwzHsAoN2tDW584PBv0zSWGw5r3/zaNUI5flXCacifFRGFplay8Gu8KyedI6l0VV6qRtr7IgM0vJ835jyMfKFfkK7Da51Y+VnOtI7/ZNrcw2p2uIIrikgaZsa4jQVDzCbTaPWCYT2zKfuYGekxdDEIuWunXIoqygfECzemfhChgjlmDsSJGRh+7JmU9IcTDiv1fZ/3jI7qlMyy8N57FLFzYkwGyQJ7ezxEAJwdUkzFKjNFcuS7Rz5fK1sMicTdXmAESMUOW448/yLCxIxzXSvFD42KEXFv2qbM+VzVTzrCw+RoHW/92AfJicw4Wszuvs6whkvaMTpPB7SfOPe6ZF1Nto6p0WCCC6dYJ78YPQi7ru6A9J4QyK0cYUYNk9HkTS01QDn3Fex3zC/lhwUfVeF1mK/IfbHS99uH3lfxJ8y77DLTT//etyyKuW1xb7Mo4NhPQ8B4lk62a3IxTEWXdp6uutdTMoRP1vgCmWwFQ5k2110cG5Ke+dILoqN6dlYt7y6yEf4CExTlQhDIZlkZQeGN1eBaIg14N2PwojmLNrq0y9OF1UrX3ap4MgoD5ys+vP58Zz7BQulO24pyo7LmT/EbdGSRheZ9TvRp2uY7jOySWLpb23UTmW+/5thH1sbj4dRTs=
  template:
    metadata:
      name: pvc-plumber-kopia
      namespace: volsync-system
