apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pvc-plumber-kopia
  namespace: volsync-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    KOPIA_PASSWORD: AgBF8fW2H/RslhcozA8uP24JHO/zKn6Al1DY6D9ZCp50Z1PD0wYs+BpIfOFMzi5rL9BPIHTM2VzC8HVQkO4+sWehoceCTt4VRMLRnU+Qlh30pvb31hCz00N6a17fswXPanNUo3okoyridr4uG0MhwV9VF7gnk/eEal1AAViOrvqk/VEaAH56P9d4VPk2vBLR+8cdMQ480qbIQcAuijh9Lh3Pqv31j8qOJckKqwUKkFbJoDxOvTG97IgXutA+lAQnoaiJUPRAEPgMlXEFUCz/rChOTeE6S6AP5F2CAnbytqv31Yvo/f73wX2APWu261VRqrDwpEpWGe16kGeMNjvcNqhMSzqVq4AjYToNLySMUZJdC7C4aOh1nh5/F5W7pwdTcyvij/3UYCDRE21gDVMLe2xhgZJS1Es/uUhC1XO+8b0MveEkp1DULKqnPns4EVws9kYLXSUiTvtr8lodAVWIgKbD4Nfjc0GABTF+etsf414N9kKOcvIZFQIiLj4UOehviC2r2ZwNDhctbJa4UOzFt5Qq/k8JNbjPzhnQo8xku+iAIucsum5a+OtK2QgPIG/4fDpUuuB5Wive0S2S6yqwQZXlrIf4bQ4ecGIcXQEa4K2lruQmGzPkGEhSewxswgC+i0vPb5e/EyUmuyAgzCNqOpEGUwYBjFuIKvpKTsuu4RET1L3GOhDhMDd5KCroK0DcU5r/g9WNG0bEpbo
  template:
    metadata:
      name: pvc-plumber-kopia
      namespace: volsync-system
