apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pvc-plumber-kopia
  namespace: volsync-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    KOPIA_PASSWORD: AgAyLGQmWVRgIzqEPp0R0Z2MBlliPp5504P6MYKsJgPb6fYZlahvUtMUyOazyf445Fq8a4DcyA4TAZCYFaY7zbMo07Zx8cHNPeKwk8IpsUhyW7xyD9yXkYG7j4BSIZydPOvmJMHBhxR0Ht29/Kq0g4kHlsnlX6SzDXcjaqv/KAZY2Fi4iyjT4tacKaaJ0w+cT2qLEZOktqO/1l99u+SLXOVqIyynvUDtoBlVyHFnLrM7zAOxbCIouEh9kLUCj38nu6y3GDTMq4BkhcgzoGfCoc7AbRLTjx9iClBWriTjBQCF9ApHDcUhjxyJGl78MTGeWKJtMY5OkDRw7nIsTZXDmL4pSGhn2tWAazX6P9crw/WEDhUeEl22kOuSZnFYBSfGZTts5xdqMkzgEqE6fgyY3jpi8jRc/IFm1u5mJB0yUtjFGl9f85xhkbTt7ZT6P6teY6gjTWRyyX/91yCRUibjGj2z03Ted96F2qnKbhdXPhTKDRtLGYTRxbZkFXbNX7YiqMWzNDGipljOq0CMGKYoZgt9zrwQ04cN5HD4Z65xKT8usBbo+XIr85vPcU/L/l7YkpPgLDpsSSW/j2lUGpTzpoMiTmC45XiZfcNBF6RrZN5bB0rfd4Ihd72xvl1ETwMKund73VJHyfB6ZbWdN7An75SpvrUykZr+pZrTVQVUILKtClVoPrtaWcijUbjBFGiutSOAigwd0yvr
  template:
    metadata:
      name: pvc-plumber-kopia
      namespace: volsync-system
