apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audit-service/rbac.yaml
  - audit-service/pvc.yaml
  - audit-service/service.yaml
  - audit-service/deployment.yaml
  - tetragon-forwarder/rbac.yaml
  - tetragon-forwarder/daemonset.yaml
  - tracing-policies/exec-audit.yaml
  - tracing-policies/network-audit.yaml
