# DB password for the Backstage app — lives in backstage namespace.
# Must contain the same password as backstage-app-secret in cloudnative-pg namespace.
#
# Regenerate:
#   kubectl create secret generic backstage-db \
#     --namespace backstage \
#     --from-literal=POSTGRES_PASSWORD=<SAME_PASSWORD_AS_backstage-app-secret> \
#     --dry-run=client -o yaml | \
#     kubeseal --controller-name=sealed-secrets --controller-namespace=sealed-secrets --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-db
  namespace: backstage
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAaVgW7QKadRLQkAZhJDBMgbECbF77k9haWjN1jgDq0oTe6PyWFwVOsJ8UHNw3UoISqHsByhWAldFA9Xo8YtEnDhYCk4eW8KXE7ImWs/GcqbqCpDTFPDRgduSGndCvJwDNLKhBloegbKbp81z5SOfHZ6ySy91unWA558B5pgkPoXhpz/JnNg1WE+7lqSnrYx/YxJGBdUPeC7Qv7uHl7otYMBif90E5V8K3dnqWlnUNSONToD12mhJnsBqk/mGIlBjg6/P8mLKunJXJ263s4ieIDOQVUo9H3V82q8GSk/67vUq6r6WPGiOR2H0dBs5pJPiC+Pzm5xnUAGZyfRl5GHYUd5xa/pOI8WcbxsCdph+nvD7lZ7zNtWk7gWslI7TbnRrZxz/L+Hv0dQ9zMUprvHYZFjTQYP4iRKlyEAftl12kxyODc2jUK1sRr2CDtALmmeYBzU1Ydsj80S+HOLShNSC9fxGMlROpTB3gLBTn8jAev7h2zaBgf8mrVizg+2xf4deFyzl/D6Jnx7pQXUQfnkSSNsdRTWzefdSXBLeBr8sg4o9nxZFfAMZ1OLyReaJd5VVdb1UT3U2VafYUalxxookgM98xgiVH2ToP+2P3GZ30jMz494rx56MYwLiPuqurlrlq/LwEz/MkRIdknujmu6pcZ6Y77KY3EiMDDjJ2iYSUrOcG+AyLfdybL774ASaOnJ9pi2Gtr9WhyHlQNrOU8XVoXdiC04sXcn0dyW4h2K5325Q==
  template:
    metadata:
      name: backstage-db
      namespace: backstage
