apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage

resources:
  - namespace.yaml
  - httproute.yaml
  - sealedsecret.yaml
  - db-sealedsecret.yaml

helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 2.7.0
    releaseName: backstage
    namespace: backstage
    valuesFile: values.yaml

patches:
  - target:
      kind: Deployment
      name: backstage
    patch: |
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: harbor-pull-secret
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
        value: 10
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 60
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
        value: 10
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
        value: 60
