apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frigate-secrets
  namespace: frigate
spec:
  encryptedData:
    FRIGATE_MQTT_USER: REPLACE_ME
    FRIGATE_MQTT_PASSWORD: REPLACE_ME
    NEST_CLIENT_ID: REPLACE_ME
    NEST_CLIENT_SECRET: REPLACE_ME
    NEST_PROJECT_ID: REPLACE_ME
    NEST_REFRESH_TOKEN: REPLACE_ME
  template:
    metadata:
      name: frigate-secrets
      namespace: frigate
