apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zomboid-secrets
  namespace: project-zomboid
spec:
  encryptedData:
    admin-username: REPLACE_ME
    admin-password: REPLACE_ME
    server-password: REPLACE_ME
    rcon-password: REPLACE_ME
  template:
    metadata:
      name: zomboid-secrets
      namespace: project-zomboid
