apiVersion: v1
kind: Service
metadata:
  name: project-zomboid
  namespace: project-zomboid
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.51
  selector:
    app: project-zomboid
  ports:
    - name: game
      port: 16261
      targetPort: 16261
      protocol: UDP
    - name: game2
      port: 16262
      targetPort: 16262
      protocol: UDP
    - name: rcon
      port: 27015
      targetPort: 27015
      protocol: TCP
