---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-app-secret
  namespace: cloudnative-pg
spec:
  encryptedData:
    password: AgBiFzKg9EGddKKwrm5NA99lvNLnu7uzPoyVEzMtVxM0ilaEJMlqjptwXTF+vuoHxKsszmra/qYSvzn5jcfR67AN+xaeRLAFLuOQQ1UyOJK4aNtRUn5CRhiKt4f1BB9VBSXK9+0Gg4w9BYRfo0wzhEioIx9CL4BGezwZ1uRamKCNYCr9VOxhR7FVC5tl42mKotX5nGxMwCONzh+pXgU9QjqZUCWsysYJB1OPl1N8egz1lZ5hQfE/7bKbIzqlJV/CP3fshGgXqiqgUZv/DTgxzi2lF+b5FIhW/cQf3JduINyoiGOgZQhH9a0RD2mRX7dGt2aVcQPxfoMb7QqMg2nYLZlciw/h8THthGI35euaq+SXH0xCyrAI6QZQSo1Cmx3jCSWBeBCCb/GkS7l9T3QHLZRLznz0qDciFrvmaQDLVnUldTJBVEQty/Ja8pwQCZS5CTgrYkHwPhsl6AgKXj+bjCqKzemNsn29Mv7kJc6WVaJG+tz2taXEs/GkxgGOlJikHCc7x5+w2BrGG5OqtvbKPjJ638RBvs5XQ8xwU3i0wQ3h/4UlyQfnbr2qQWNPpIuUZMMo+sWEblh9ymxEDqDWYAwrnp+1nzl69fiB8L5Sk8SbvnY1cUD/76jj29Ozvx19OqaNcEAC6r1jTCKg/mtRquJZewryHOL+ugvm41D4HU7/Qkt8ylHUCTcVVDtJ6iUjaNl/OtiMBN+l
    username: AgB2oX7RlOwVo8B+OluFUJUqoSAv/SagpnQmeGicGjb/Qxsx0sm3B22/8yw7a/P7qydQCSIQXaTEfzi7YjPuPnz2LcdSYAfiuURrvKbjmiAgkKvEJ8S6H8inYyYF29RUvMRw7mjVbYgTxN/fmLOWCz8RJKyYmYN1u/vBsMEAt0c9tjOEroOfw8SL1vbWvTd7dwtQLRFd5sj1XN8dlwxzDxe617VODHv2hqAVPG3JhbRHb9G8/ERYPEzIMvmdvjJ6899v/f7BQXsBz6A3lK5eiVUuIHkeZlNNxP1HipntOAfZQwwu8Pfr1my0/R/pV8LlWzacuzdO5+ckTHdtkLMYMX3bOhQ/KMMN1p12UREbsJJUPArrODsiD3jjL2EbZ7LtLIwamORt9uzaP2gZNBDWJiEF9FLh2MZk+e2cX8cw4klDAF4PPU5q2Q+WYVzC3cpsvtCXcwfP4mfQlPagjhT2RRBBlpls/LMOAY0LMOTZccykHo9+H8apkzh/wvsDQOSfpiDjtYWab/HUgbrB3Smp69vfrZC/3DO9DHgdXl3vBJBd/q85cppm2q0pJtiAJJ73nyq6oTtS1Ou7PzMrdC7ym6minsvcc1Gp+sf+XJn5QY+X3I8sMdZBJkDuuyPn8QWyhYUA2hIK+UUPYtyGCiVcK4x+eTufOX3zIKQFuUEJ+TAwrfbZmsZxSUUTEz8RSAQHXQnJwGNVtw==
  template:
    metadata:
      name: gitea-app-secret
      namespace: cloudnative-pg
