apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - token-service/rbac.yaml
  - token-service/authorized-roles-configmap.yaml
  - token-service/deployment.yaml
  - token-service/service.yaml
