apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: comfyui-secrets
  namespace: comfyui
spec:
  encryptedData:
    HF_TOKEN: REPLACE_ME
    CIVITAI_TOKEN: REPLACE_ME
    CIVITAI_NSFW_TOKEN: REPLACE_ME
  template:
    metadata:
      name: comfyui-secrets
      namespace: comfyui
