apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redlib-secrets
  namespace: redlib
spec:
  encryptedData:
    POSTHOG_API_KEY: REPLACE_ME
  template:
    metadata:
      name: redlib-secrets
      namespace: redlib
