apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-app-secret
  namespace: cloudnative-pg
spec:
  encryptedData:
    username: REPLACE_ME
    password: REPLACE_ME
  template:
    metadata:
      name: immich-app-secret
      namespace: cloudnative-pg
