apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: tubesync
  labels:
    backup: "daily"
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: tubesync
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: tubearchivist-smb
  resources:
    requests:
      storage: 1Ti
